import {env} from "cloudflare:workers";
import {and,eq} from "drizzle-orm";
import {getChatGPTUser} from "@/app/chatgpt-auth";
import {getDb} from "@/db";
import {garantirBanco} from "@/db/bootstrap";
import {associacoes,documentosAssociacao} from "@/db/schema";
import {isAdminEmail} from "@/lib/admin";
export const runtime="edge";
type Arquivo={key:string;nome:string;tipo:string;descricao?:string;quantidade?:string;valor?:string;dataEmissao?:string};
type DadosNota=Pick<Arquivo,"descricao"|"quantidade"|"valor"|"dataEmissao">;
async function salvar(files:File[],pasta:string,userId:string,dados:DadosNota[]=[]){const itens:Arquivo[]=[];for(const [indice,file] of files.entries()){if(file.size>10*1024*1024)throw new Error(`O ARQUIVO ${file.name} DEVE TER NO MÁXIMO 10 MB.`);if(!["application/pdf","image/jpeg","image/png"].includes(file.type))throw new Error(`FORMATO NÃO PERMITIDO: ${file.name}.`);const key=`associacoes-financeiro/${userId}/${pasta}/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,"_")}`;await env.BUCKET.put(key,await file.arrayBuffer(),{metadata:{contentType:file.type}});itens.push({key,nome:file.name,tipo:file.type,...dados[indice]});}return itens;}
export async function POST(request:Request){await garantirBanco();const user=await getChatGPTUser();const acessoGeral=!!user&&(isAdminEmail(user.email)||user.role==="admin"||user.role==="aderes");if(!user||(user.role!=="associacao"&&!acessoGeral)||(!user.associacao&&!acessoGeral))return Response.json({message:"ACESSO RESTRITO À ASSOCIAÇÃO OU ADERES."},{status:403});try{const form=await request.formData();const db=getDb();let associacao=user.associacao||"";if(acessoGeral){const solicitada=String(form.get("associacao")||"").trim();const valida=await db.query.associacoes.findFirst({where:and(eq(associacoes.nome,solicitada),eq(associacoes.ativo,true))});if(!valida)return Response.json({message:"SELECIONE UMA ASSOCIAÇÃO VÁLIDA."},{status:400});associacao=valida.nome;}const competencia=String(form.get("competencia")||"");if(!/^\d{4}-\d{2}$/.test(competencia))return Response.json({message:"INFORME UMA COMPETÊNCIA VÁLIDA."},{status:400});const extratos=form.getAll("extratos").filter((x):x is File=>x instanceof File&&x.size>0);const notas=form.getAll("notasFiscais").filter((x):x is File=>x instanceof File&&x.size>0);let dadosNotas:DadosNota[]=[];try{const dados=JSON.parse(String(form.get("dadosNotas")||"[]"));if(Array.isArray(dados))dadosNotas=dados;}catch{}if(notas.some((_,i)=>!dadosNotas[i]?.descricao||!dadosNotas[i]?.valor||!dadosNotas[i]?.dataEmissao))return Response.json({message:"INFORME DESCRIÇÃO, VALOR E DATA DE EMISSÃO DE CADA NOTA FISCAL."},{status:400});if(!extratos.length&&!notas.length)return Response.json({message:"INCLUA PELO MENOS UM EXTRATO BANCÁRIO OU UMA NOTA FISCAL."},{status:400});const existente=await db.query.documentosAssociacao.findFirst({where:and(eq(documentosAssociacao.associacao,associacao),eq(documentosAssociacao.competencia,competencia))});let extratosAtuais:Arquivo[]=[];let notasAtuais:Arquivo[]=[];try{extratosAtuais=JSON.parse(existente?.extratosJson||"[]")}catch{}try{notasAtuais=JSON.parse(existente?.notasFiscaisJson||"[]")}catch{}const novosExtratos=await salvar(extratos,`extratos/${competencia}`,user.userId);const novasNotas=await salvar(notas,`notas/${competencia}`,user.userId,dadosNotas);const values={authUserId:user.userId,associacao,competencia,extratosJson:JSON.stringify([...extratosAtuais,...novosExtratos]),notasFiscaisJson:JSON.stringify([...notasAtuais,...novasNotas]),atualizadoEm:new Date().toISOString()};if(existente)await db.update(documentosAssociacao).set(values).where(eq(documentosAssociacao.id,existente.id));else await db.insert(documentosAssociacao).values(values);return Response.json({message:"DOCUMENTOS SALVOS COM SUCESSO."});}catch(error){return Response.json({message:error instanceof Error?error.message:"NÃO FOI POSSÍVEL SALVAR OS DOCUMENTOS."},{status:500});}}
