import {env} from "cloudflare:workers";
import {and,eq} from "drizzle-orm";
import {getChatGPTUser} from "@/app/chatgpt-auth";
import {getDb} from "@/db";
import {garantirBanco} from "@/db/bootstrap";
import {associacoes,documentosAssociacao} from "@/db/schema";
import {isAdminEmail} from "@/lib/admin";
export const runtime="edge";
type Arquivo={key:string;nome:string;tipo:string;descricao?:string;quantidade?:string;valor?:string;dataEmissao?:string};
type DadosNota=Pick<Arquivo,"descricao"|"quantidade"|"valor"|"dataEmissao">;
type DocumentoRecebido={file:File;grupo:"extrato"|"nota";dados?:DadosNota};
const meses:Record<string,string>={JANEIRO:"01",FEVEREIRO:"02",MARCO:"03",ABRIL:"04",MAIO:"05",JUNHO:"06",JULHO:"07",AGOSTO:"08",SETEMBRO:"09",OUTUBRO:"10",NOVEMBRO:"11",DEZEMBRO:"12"};
function normalizar(valor:string){return valor.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toUpperCase().replace(/[^A-Z0-9]+/g," ").trim()}
function competenciaDoArquivo(nome:string,dataEmissao?:string){
 const texto=normalizar(nome);let achado=texto.match(/\b(20\d{2})\s+(0?[1-9]|1[0-2])\b/);if(achado)return `${achado[1]}-${achado[2].padStart(2,"0")}`;
 achado=texto.match(/\b(0?[1-9]|1[0-2])\s+(20\d{2})\b/);if(achado)return `${achado[2]}-${achado[1].padStart(2,"0")}`;
 achado=texto.match(/\b([0-3]?\d)\s+(0?[1-9]|1[0-2])\s+(20\d{2})\b/);if(achado)return `${achado[3]}-${achado[2].padStart(2,"0")}`;
 achado=texto.match(/\b([0-3]\d)(0[1-9]|1[0-2])(20\d{2})\b/);if(achado)return `${achado[3]}-${achado[2]}`;
 for(const [mes,numero] of Object.entries(meses)){const ano=texto.match(new RegExp(`\\b${mes}\\s+(20\\d{2})\\b`));if(ano)return `${ano[1]}-${numero}`;}
 return /^20\d{2}-(0[1-9]|1[0-2])-\d{2}$/.test(dataEmissao||"")?dataEmissao!.slice(0,7):"";
}
function associacaoDoArquivo(nome:string,lista:Array<typeof associacoes.$inferSelect>){const texto=normalizar(nome).replace(/\s/g,"");return [...lista].sort((a,b)=>normalizar(b.nome).replace(/\s/g,"").length-normalizar(a.nome).replace(/\s/g,"").length).find(item=>{const sigla=normalizar(item.nome).replace(/\s/g,"");const razao=normalizar(item.razaoSocial||"").replace(/\s/g,"");const cnpj=(item.cnpj||"").replace(/\D/g,"");return texto.includes(sigla)||(razao.length>=6&&texto.includes(razao))||(cnpj.length===14&&texto.includes(cnpj));})?.nome||""}
async function salvar(files:File[],pasta:string,userId:string,dados:DadosNota[]=[]){const itens:Arquivo[]=[];for(const [indice,file] of files.entries()){if(file.size>10*1024*1024)throw new Error(`O ARQUIVO ${file.name} DEVE TER NO MÁXIMO 10 MB.`);if(!["application/pdf","image/jpeg","image/png"].includes(file.type))throw new Error(`FORMATO NÃO PERMITIDO: ${file.name}.`);const key=`associacoes-financeiro/${userId}/${pasta}/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,"_")}`;await env.BUCKET.put(key,await file.arrayBuffer(),{metadata:{contentType:file.type}});itens.push({key,nome:file.name,tipo:file.type,...dados[indice]});}return itens;}
export async function POST(request:Request){await garantirBanco();const user=await getChatGPTUser();const acessoGeral=!!user&&(isAdminEmail(user.email)||user.role==="admin"||user.role==="aderes");if(!user||(user.role!=="associacao"&&!acessoGeral)||(!user.associacao&&!acessoGeral))return Response.json({message:"ACESSO RESTRITO À ASSOCIAÇÃO OU ADERES."},{status:403});try{const form=await request.formData();const db=getDb();const listaAssociacoes=await db.select().from(associacoes).where(eq(associacoes.ativo,true));const extratos=form.getAll("extratos").filter((x):x is File=>x instanceof File&&x.size>0);const notas=form.getAll("notasFiscais").filter((x):x is File=>x instanceof File&&x.size>0);let dadosNotas:DadosNota[]=[];try{const dados=JSON.parse(String(form.get("dadosNotas")||"[]"));if(Array.isArray(dados))dadosNotas=dados;}catch{}if(notas.some((_,i)=>!dadosNotas[i]?.descricao||!dadosNotas[i]?.valor||!dadosNotas[i]?.dataEmissao))return Response.json({message:"INFORME DESCRIÇÃO, VALOR E DATA DE EMISSÃO DE CADA NOTA FISCAL."},{status:400});if(!extratos.length&&!notas.length)return Response.json({message:"INCLUA PELO MENOS UM EXTRATO BANCÁRIO OU UMA NOTA FISCAL."},{status:400});
 const recebidos:DocumentoRecebido[]=[...extratos.map(file=>({file,grupo:"extrato" as const})),...notas.map((file,i)=>({file,grupo:"nota" as const,dados:dadosNotas[i]}))];
 const identificados=recebidos.map(item=>({...item,associacao:user.role==="associacao"?user.associacao||"":associacaoDoArquivo(item.file.name,listaAssociacoes),competencia:competenciaDoArquivo(item.file.name,item.dados?.dataEmissao)}));
 const invalidos=identificados.filter(item=>!item.associacao||!item.competencia);if(invalidos.length)return Response.json({message:`NÃO FOI POSSÍVEL IDENTIFICAR ${invalidos.map(item=>`${item.file.name} (${!item.associacao?"ASSOCIAÇÃO":""}${!item.associacao&&!item.competencia?" E ":""}${!item.competencia?"COMPETÊNCIA":""})`).join("; ")}. INCLUA A SIGLA DA ASSOCIAÇÃO E O MÊS/ANO NO NOME DO ARQUIVO.`},{status:400});
 const grupos=new Map<string,typeof identificados>();for(const item of identificados){const chave=`${item.associacao}|${item.competencia}`;grupos.set(chave,[...(grupos.get(chave)||[]),item]);}
 for(const itens of grupos.values()){const {associacao,competencia}=itens[0];const existente=await db.query.documentosAssociacao.findFirst({where:and(eq(documentosAssociacao.associacao,associacao),eq(documentosAssociacao.competencia,competencia))});let extratosAtuais:Arquivo[]=[];let notasAtuais:Arquivo[]=[];try{extratosAtuais=JSON.parse(existente?.extratosJson||"[]")}catch{}try{notasAtuais=JSON.parse(existente?.notasFiscaisJson||"[]")}catch{}const itensExtrato=itens.filter(item=>item.grupo==="extrato");const itensNota=itens.filter(item=>item.grupo==="nota");const novosExtratos=await salvar(itensExtrato.map(item=>item.file),`extratos/${competencia}`,user.userId);const novasNotas=await salvar(itensNota.map(item=>item.file),`notas/${competencia}`,user.userId,itensNota.map(item=>item.dados||{}));const values={authUserId:user.userId,associacao,competencia,extratosJson:JSON.stringify([...extratosAtuais,...novosExtratos]),notasFiscaisJson:JSON.stringify([...notasAtuais,...novasNotas]),atualizadoEm:new Date().toISOString()};if(existente)await db.update(documentosAssociacao).set(values).where(eq(documentosAssociacao.id,existente.id));else await db.insert(documentosAssociacao).values(values);}
 return Response.json({message:`${recebidos.length} DOCUMENTO(S) SALVO(S) COM ASSOCIAÇÃO E COMPETÊNCIA IDENTIFICADAS AUTOMATICAMENTE.`});}catch(error){return Response.json({message:error instanceof Error?error.message:"NÃO FOI POSSÍVEL SALVAR OS DOCUMENTOS."},{status:500});}}
