"use client";
import { useState } from "react";
import { Pencil, Plus, Trash2, X } from "lucide-react";
import { MUNICIPIOS_ES } from "@/lib/municipios-es";

type Associacao={id:number;nome:string;razaoSocial:string|null;cnpj:string|null;cep:string|null;endereco:string|null;telefone:string|null;celular:string|null;municipiosJson:string};
type Formulario={id?:number;nome:string;razaoSocial:string;cnpj:string;cep:string;endereco:string;telefone:string;celular:string;municipios:string[]};
const vazio:Formulario={nome:"",razaoSocial:"",cnpj:"",cep:"",endereco:"",telefone:"",celular:"",municipios:[]};
const lerMunicipios=(json:string)=>{try{return JSON.parse(json) as string[];}catch{return[];}};

export default function AssociacoesClient({itens}:{itens:Associacao[]}){
  const[form,setForm]=useState<Formulario>(vazio);const[municipio,setMunicipio]=useState("");const[msg,setMsg]=useState("");const[loading,setLoading]=useState(false);
  const campo="mt-1 h-10 w-full rounded-lg border border-slate-300 px-3 text-sm";
  function editar(a:Associacao){setForm({id:a.id,nome:a.nome,razaoSocial:a.razaoSocial||"",cnpj:a.cnpj||"",cep:a.cep||"",endereco:a.endereco||"",telefone:a.telefone||"",celular:a.celular||"",municipios:lerMunicipios(a.municipiosJson)});setMsg("");}
  async function salvar(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);setMsg("");const fd=new FormData(e.currentTarget);if(form.id)fd.set("id",String(form.id));fd.set("municipios",JSON.stringify(form.municipios));const r=await fetch("/api/admin/associacoes",{method:form.id?"PUT":"POST",body:fd});const b=await r.json();setMsg(b.message);if(r.ok)location.reload();setLoading(false);}
  async function remover(id:number){if(!confirm("Desativar esta associação?"))return;const r=await fetch(`/api/admin/associacoes?id=${id}`,{method:"DELETE"});if(r.ok)location.reload();}
  function incluirMunicipio(){if(municipio&&!form.municipios.includes(municipio)){setForm(f=>({...f,municipios:[...f.municipios,municipio].sort()}));setMunicipio("");}}
  return <section className="rounded-2xl border bg-white p-5 shadow-sm lg:col-span-2"><div className="flex items-center justify-between"><div><h2 className="text-lg font-bold">Cadastro de associações</h2><p className="text-sm text-slate-600">Dados cadastrais e municípios atendidos.</p></div>{form.id&&<button type="button" onClick={()=>setForm(vazio)} className="text-sm font-bold text-slate-600">Cancelar edição</button>}</div>
    <form onSubmit={salvar} className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><label className="text-sm font-semibold">Nome abreviado *<input name="nome" required value={form.nome} onChange={e=>setForm(f=>({...f,nome:e.target.value}))} className={campo}/></label><label className="text-sm font-semibold sm:col-span-2">Razão social *<input name="razaoSocial" required value={form.razaoSocial} onChange={e=>setForm(f=>({...f,razaoSocial:e.target.value}))} className={campo}/></label><label className="text-sm font-semibold">CNPJ *<input name="cnpj" required value={form.cnpj} onChange={e=>setForm(f=>({...f,cnpj:e.target.value}))} className={campo} placeholder="00.000.000/0000-00"/></label><label className="text-sm font-semibold">CEP *<input name="cep" required value={form.cep} onChange={e=>setForm(f=>({...f,cep:e.target.value}))} className={campo}/></label><label className="text-sm font-semibold sm:col-span-2">Endereço *<input name="endereco" required value={form.endereco} onChange={e=>setForm(f=>({...f,endereco:e.target.value}))} className={campo}/></label><label className="text-sm font-semibold">Telefone<input name="telefone" value={form.telefone} onChange={e=>setForm(f=>({...f,telefone:e.target.value}))} className={campo}/></label><label className="text-sm font-semibold">Celular *<input name="celular" required value={form.celular} onChange={e=>setForm(f=>({...f,celular:e.target.value}))} className={campo}/></label>
      <div className="sm:col-span-2 lg:col-span-4"><label className="text-sm font-semibold">Municípios atendidos *</label><div className="mt-1 flex gap-2"><select value={municipio} onChange={e=>setMunicipio(e.target.value)} className={`${campo} mt-0 flex-1`}><option value="">Selecione entre os 78 municípios</option>{MUNICIPIOS_ES.filter(m=>!form.municipios.includes(m)).map(m=><option key={m}>{m}</option>)}</select><button type="button" onClick={incluirMunicipio} className="rounded-lg border border-emerald-700 px-4 font-bold text-emerald-800">Incluir</button></div><div className="mt-2 flex flex-wrap gap-2">{form.municipios.map(m=><span key={m} className="inline-flex items-center gap-2 rounded-full bg-emerald-100 px-3 py-1 text-sm font-semibold text-emerald-900">{m}<button type="button" onClick={()=>setForm(f=>({...f,municipios:f.municipios.filter(x=>x!==m)}))} aria-label={`Remover ${m}`}><X className="h-3.5 w-3.5"/></button></span>)}</div></div>
      <div className="sm:col-span-2 lg:col-span-4 flex items-center gap-3"><button disabled={loading} className="inline-flex h-11 items-center gap-2 rounded-lg bg-emerald-700 px-5 font-bold text-white"><Plus className="h-4 w-4"/>{form.id?"Salvar alterações":"Cadastrar associação"}</button>{msg&&<p className="text-sm">{msg}</p>}</div></form>
    <div className="mt-6 grid gap-3 sm:grid-cols-2">{itens.map(a=><article key={a.id} className="rounded-xl border bg-slate-50 p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-bold">{a.nome}</p><p className="text-sm text-slate-600">{a.razaoSocial||"Cadastro a completar"}</p><p className="mt-1 text-xs text-slate-500">CNPJ: {a.cnpj||"não informado"} · {lerMunicipios(a.municipiosJson).length} município(s)</p></div><div className="flex gap-2"><button onClick={()=>editar(a)} aria-label={`Editar ${a.nome}`} className="text-blue-800"><Pencil className="h-4 w-4"/></button><button onClick={()=>remover(a.id)} aria-label={`Desativar ${a.nome}`} className="text-red-700"><Trash2 className="h-4 w-4"/></button></div></div></article>)}</div>
  </section>;
}
