"use client";
import { useState } from "react";
import { Plus, X } from "lucide-react";
import { MUNICIPIOS_ES } from "@/lib/municipios-es";

const TIPOS=["CAFÉ CONILON","CAFÉ ARÁBICA","CACAU","BANANA-DA-TERRA","BANANA","MARACUJÁ","PIMENTA-DO-REINO","CITROS","MANGA","GOIABA","ABACATE","PALMÁCEAS","UVA","ACEROLA","MANDIOCA","PISCICULTURA","HORTICULTURA","AQUAPONIA","APICULTURA","HIDROPONIA"];
export default function NovaEntregaMudas({colaboradores,competencia}:{colaboradores:Array<{authUserId:string;nomeCompleto:string;associacao:string|null}>;competencia:string}){
 const[aberto,setAberto]=useState(false),[msg,setMsg]=useState(""),[salvando,setSalvando]=useState(false);
 async function salvar(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setSalvando(true);setMsg("");const r=await fetch("/api/admin/entregas-mudas",{method:"POST",body:new FormData(e.currentTarget)});const b=await r.json().catch(()=>({}));setMsg(b.message||"NÃO FOI POSSÍVEL SALVAR.");setSalvando(false);if(r.ok)setTimeout(()=>location.reload(),600);}
 return <><button onClick={()=>setAberto(true)} className="inline-flex h-11 items-center gap-2 rounded-lg bg-amber-400 px-4 text-sm font-black text-emerald-950"><Plus className="h-4 w-4"/>INCLUIR NOVA ENTREGA DE MUDAS</button>{aberto&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/50 p-4"><form onSubmit={salvar} className="max-h-[92vh] w-full max-w-2xl overflow-y-auto rounded-2xl bg-white p-6 text-slate-900 shadow-2xl"><div className="flex items-center justify-between"><h2 className="text-xl font-black">NOVA ENTREGA DE MUDAS</h2><button type="button" onClick={()=>setAberto(false)}><X/></button></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold">COMPETÊNCIA<input name="competencia" type="month" required defaultValue={competencia} className="mt-1 h-11 w-full rounded-lg border px-3"/></label><label className="text-sm font-bold">COLABORADOR<select name="authUserId" required className="mt-1 h-11 w-full rounded-lg border bg-white px-3"><option value="">SELECIONE</option>{colaboradores.map(c=><option key={c.authUserId} value={c.authUserId}>{c.nomeCompleto} · {c.associacao||"SEM ASSOCIAÇÃO"}</option>)}</select></label><label className="text-sm font-bold">DATA DA ENTREGA<input name="data" type="date" required className="mt-1 h-11 w-full rounded-lg border px-3"/></label><label className="text-sm font-bold">MUNICÍPIO<select name="municipio" required className="mt-1 h-11 w-full rounded-lg border bg-white px-3"><option value="">SELECIONE</option>{MUNICIPIOS_ES.map(m=><option key={m}>{m}</option>)}</select></label><label className="text-sm font-bold">TIPO DE MUDA<select name="tipoMuda" required className="mt-1 h-11 w-full rounded-lg border bg-white px-3"><option value="">SELECIONE</option>{TIPOS.map(t=><option key={t}>{t}</option>)}</select></label><label className="text-sm font-bold">QUANTIDADE<input name="quantidade" type="number" min="1" step="1" required className="mt-1 h-11 w-full rounded-lg border px-3"/></label></div><label className="mt-4 block text-sm font-bold">OBSERVAÇÃO<textarea name="observacao" className="mt-1 min-h-24 w-full rounded-lg border p-3"/></label><button disabled={salvando} className="mt-5 h-12 w-full rounded-xl bg-emerald-800 font-black text-white disabled:opacity-50">{salvando?"SALVANDO...":"SALVAR ENTREGA"}</button>{msg&&<p className="mt-3 rounded-lg bg-slate-100 p-3 text-sm font-bold">{msg}</p>}</form></div>}</>;
}
