import { redirect } from "next/navigation";
import { Download, FileCheck2, FileClock, Users } from "lucide-react";
import { getDb } from "@/db";
import { associacoes, colaboradores, planosTrabalho, prestacoes, usuariosAcesso } from "@/db/schema";
import { getAdminUser } from "@/lib/admin";
import AssociacoesClient from "./associacoes-client";
import UsuariosAcesso from "./usuarios-acesso-client";
import SenhaAdmin from "./senha-admin-client";

export const dynamic="force-dynamic";

function competenciaAtual(){const d=new Date();return `${d.getUTCFullYear()}-${String(d.getUTCMonth()+1).padStart(2,"0")}`;}
function formatarData(data:string){const partes=data.split("-");return partes.length===3?`${partes[2]}/${partes[1]}/${partes[0]}`:data;}

export default async function AdminPage({searchParams}:{searchParams:Promise<{competencia?:string;mudas?:string;aba?:string}>}){
  const admin=await getAdminUser();if(!admin)redirect("/");
  const params=await searchParams;const competencia=/^\d{4}-\d{2}$/.test(params.competencia||"")?params.competencia!:competenciaAtual();const abasValidas=new Set(["resumo","prestacoes","planos","associacoes","usuarios","acessos","pendencias"]);const aba=abasValidas.has(params.aba||"")?params.aba!:"resumo";
  const db=getDb();
  const [usuarios,todosPlanos,todasPrestacoes,listaAssociacoes,acessos]=await Promise.all([db.select().from(colaboradores),db.select().from(planosTrabalho),db.select().from(prestacoes),db.select().from(associacoes),db.select().from(usuariosAcesso)]);
  const planos=todosPlanos.filter(p=>p.competencia===competencia);const relatorios=todasPrestacoes.filter(p=>p.competencia===competencia);
  const mudasTodas=params.mudas==="todas";const relatoriosMudas=mudasTodas?todasPrestacoes:relatorios;
  const nomes=new Map(usuarios.map(u=>[u.authUserId,u]));const comPlano=new Set(planos.map(p=>p.authUserId));const comPrestacao=new Set(relatorios.map(p=>p.authUserId));
  const hoje=new Date().toISOString().slice(0,10);const vencidos=usuarios.filter(u=>u.documentoValidade<hoje);
  const cargos=Object.entries(usuarios.reduce<Record<string,number>>((acc,u)=>{acc[u.cargo]=(acc[u.cargo]||0)+1;return acc;},{})).sort((a,b)=>a[0].localeCompare(b[0]));
  const mudasPorMunicipio=new Map<string,{quantidade:number;datas:Set<string>;tipos:Map<string,number>}>();
  for(const relatorio of relatoriosMudas){let atividades:Array<Record<string,unknown>>=[];try{atividades=JSON.parse(relatorio.atividadesJson);}catch{}for(const atividade of atividades){if(String(atividade.tipoAtividade||"").toLocaleLowerCase("pt-BR")!=="entrega de mudas"||atividade.executada===false)continue;const municipio=String(atividade.municipio||"Não informado").trim()||"Não informado";const quantidade=Number(atividade.quantidadeMudas)||0;if(quantidade<=0)continue;const tipo=String(atividade.tipoMuda||"Não informado").trim()||"Não informado";const data=String(atividade.data||"").trim();const atual=mudasPorMunicipio.get(municipio)||{quantidade:0,datas:new Set<string>(),tipos:new Map<string,number>()};atual.quantidade+=quantidade;if(data)atual.datas.add(data);atual.tipos.set(tipo,(atual.tipos.get(tipo)||0)+quantidade);mudasPorMunicipio.set(municipio,atual);}}
  const resumoMudas=[...mudasPorMunicipio.entries()].sort((a,b)=>b[1].quantidade-a[1].quantidade||a[0].localeCompare(b[0]));
  const totalMudas=resumoMudas.reduce((total,[,dados])=>total+dados.quantidade,0);
  const indicadores=[
    {rotulo:"Usuários",valor:usuarios.length,Icon:Users},
    {rotulo:"Planos",valor:planos.length,Icon:FileCheck2},
    {rotulo:"Prestações",valor:relatorios.length,Icon:FileCheck2},
    {rotulo:"Sem plano",valor:usuarios.length-comPlano.size,Icon:FileClock},
    {rotulo:"Sem prestação",valor:usuarios.length-comPrestacao.size,Icon:FileClock},
    {rotulo:"Docs. vencidos",valor:vencidos.length,Icon:FileClock},
  ];
  return <main className="min-h-screen bg-slate-100 text-slate-900"><header className="bg-[#123b2a] text-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4"><div><p className="font-bold">Administração · Arranjos Produtivos</p><p className="text-sm text-emerald-100">{admin.email}</p></div><a href="/" className="rounded-lg border border-white/30 px-4 py-2 text-sm font-bold">Sair do painel</a></div></header><div className="mx-auto max-w-7xl px-5 py-7">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-bold uppercase tracking-wider text-emerald-700">Acompanhamento mensal</p><h1 className="mt-1 text-3xl font-bold">Painel administrativo</h1></div><form className="flex items-end gap-2"><input type="hidden" name="aba" value={aba}/><label className="text-sm font-bold">Competência<input type="month" name="competencia" defaultValue={competencia} className="mt-1 block h-11 rounded-lg border bg-white px-3"/></label><button className="h-11 rounded-lg bg-emerald-700 px-5 font-bold text-white">Consultar</button></form></div>
    <nav className="mt-6 flex gap-2 overflow-x-auto rounded-2xl border bg-white p-2 shadow-sm">{[["resumo","Resumo e mudas"],["prestacoes","Prestações"],["planos","Planos"],["associacoes","Associações"],["usuarios","Colaboradores"],["acessos","Usuários e senhas"],["pendencias","Pendências"]].map(([id,nome])=><a key={id} href={`/admin?aba=${id}&competencia=${competencia}`} className={`whitespace-nowrap rounded-xl px-4 py-3 text-sm font-bold ${aba===id?"bg-emerald-800 text-white":"text-slate-600 hover:bg-slate-100"}`}>{nome}</a>)}</nav>
    {aba==="resumo"&&<><section className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-6">{indicadores.map(({rotulo,valor,Icon})=><article key={rotulo} className="rounded-2xl border bg-white p-4 shadow-sm"><Icon className="h-5 w-5 text-emerald-700"/><p className="mt-3 text-3xl font-black">{valor}</p><p className="text-sm font-semibold text-slate-600">{rotulo}</p></article>)}</section>
    <section className="mt-6 overflow-hidden rounded-2xl border border-emerald-200 bg-white shadow-sm"><div className="flex flex-wrap items-center justify-between gap-4 bg-emerald-950 px-5 py-5 text-white"><div><p className="text-sm font-bold uppercase tracking-wider text-emerald-200">Entrega de Mudas · {mudasTodas?"Todas as competências":competencia}</p><h2 className="mt-1 text-xl font-bold">Consolidado informado nas prestações de contas</h2><div className="mt-3 flex flex-wrap gap-2"><a href={`/admin?aba=resumo&competencia=${competencia}`} className={`rounded-lg px-3 py-2 text-sm font-bold ${!mudasTodas?"bg-white text-emerald-950":"border border-white/30 text-white"}`}>Competência selecionada</a><a href={`/admin?aba=resumo&competencia=${competencia}&mudas=todas`} className={`rounded-lg px-3 py-2 text-sm font-bold ${mudasTodas?"bg-white text-emerald-950":"border border-white/30 text-white"}`}>Todas as competências</a></div></div><div className="rounded-xl bg-white/10 px-5 py-3 text-right"><p className="text-sm text-emerald-100">Total entregue</p><p className="text-3xl font-black">{totalMudas.toLocaleString("pt-BR")} <span className="text-base font-semibold">mudas</span></p></div></div><div className="overflow-x-auto p-5"><table className="w-full text-left text-sm"><thead><tr className="border-b text-slate-500"><th className="py-2">Município</th><th>Data da entrega</th><th>Tipos e quantidades</th><th className="text-right">Total de mudas</th></tr></thead><tbody>{resumoMudas.map(([municipio,dados])=><tr key={municipio} className="border-b"><td className="py-3 font-bold">{municipio}</td><td>{[...dados.datas].sort().map(formatarData).join(" · ")||"Não informada"}</td><td>{[...dados.tipos.entries()].map(([tipo,quantidade])=>`${tipo}: ${quantidade.toLocaleString("pt-BR")}`).join(" · ")}</td><td className="text-right text-base font-black text-emerald-800">{dados.quantidade.toLocaleString("pt-BR")}</td></tr>)}{!resumoMudas.length&&<tr><td colSpan={4} className="py-8 text-center text-slate-500">Nenhuma entrega de mudas executada foi informada {mudasTodas?"nas prestações cadastradas":"nesta competência"}.</td></tr>}</tbody><tfoot>{resumoMudas.length>0&&<tr className="bg-emerald-50"><td colSpan={3} className="px-3 py-3 font-bold">TOTAL GERAL</td><td className="px-3 py-3 text-right text-lg font-black text-emerald-900">{totalMudas.toLocaleString("pt-BR")}</td></tr>}</tfoot></table></div></section></>}
    {aba==="prestacoes"&&<div className="mt-6 grid gap-6 lg:grid-cols-2"><section className="rounded-2xl border bg-white p-5 shadow-sm lg:col-span-2"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-bold">Prestações de contas · {competencia}</h2><p className="text-sm text-slate-600">Download individual ou relatório consolidado.</p></div><a href={`/api/admin/prestacoes/pdf?competencia=${competencia}`} className="inline-flex items-center gap-2 rounded-lg bg-blue-800 px-4 py-2 text-sm font-bold text-white"><Download className="h-4 w-4"/>Baixar todos em PDF</a></div><div className="mt-4 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b text-slate-500"><th className="py-2">Usuário</th><th>Cargo</th><th>Associação</th><th>Atualização</th><th></th></tr></thead><tbody>{relatorios.map(r=>{const u=nomes.get(r.authUserId);return <tr key={r.id} className="border-b"><td className="py-3 font-semibold">{u?.nomeCompleto||r.authUserId}</td><td>{u?.cargo||"-"}</td><td>{r.associacao}</td><td>{r.atualizadoEm.slice(0,10)}</td><td><a href={`/api/prestacao/pdf?id=${r.id}`} className="font-bold text-blue-800">PDF</a></td></tr>})}{!relatorios.length&&<tr><td colSpan={5} className="py-8 text-center text-slate-500">Nenhuma prestação nesta competência.</td></tr>}</tbody></table></div></section></div>}\n    {aba==="associacoes"&&<AssociacoesClient itens={listaAssociacoes.filter(a=>a.ativo)}/>}
    {aba==="planos"&&<div className="mt-6 grid gap-6 lg:grid-cols-2"><section className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="text-lg font-bold">Planos de trabalho · {competencia}</h2><div className="mt-3 space-y-2">{planos.map(p=>{const u=nomes.get(p.authUserId);return <div key={p.id} className="flex items-center justify-between rounded-lg border p-3"><div><p className="font-semibold">{u?.nomeCompleto||p.authUserId}</p><p className="text-sm text-slate-500">{u?.cargo} · {p.associacao}</p></div><a href={`/api/plano/pdf?admin_id=${p.id}`} className="font-bold text-blue-800">PDF</a></div>})}{!planos.length&&<p className="py-6 text-center text-slate-500">Nenhum plano nesta competência.</p>}</div></section><section className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="text-lg font-bold">Usuários por cargo</h2><div className="mt-3 grid gap-2 sm:grid-cols-2">{cargos.map(([cargo,total])=><div key={cargo} className="flex justify-between rounded-lg bg-slate-50 px-3 py-2"><span>{cargo}</span><strong>{total}</strong></div>)}</div><h3 className="mt-6 font-bold text-amber-800">Documentos vencidos</h3><div className="mt-2 space-y-1 text-sm">{vencidos.map(u=><p key={u.id}>{u.nomeCompleto} · {u.documentoValidade}</p>)}{!vencidos.length&&<p className="text-slate-500">Nenhum documento vencido.</p>}</div></section></div>}
    {aba==="usuarios"&&<section className="mt-6 rounded-2xl border bg-white p-5 shadow-sm"><h2 className="text-lg font-bold">Cadastro de usuários por cargo</h2><p className="text-sm text-slate-600">Relação completa dos colaboradores cadastrados.</p><div className="mt-4 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b text-slate-500"><th className="py-2">Nome</th><th>E-mail</th><th>Cargo</th><th>Associação</th><th>Municípios atendidos</th><th>MEI</th><th>CFTA/CREA</th><th>Validade do documento</th></tr></thead><tbody>{[...usuarios].sort((a,b)=>a.cargo.localeCompare(b.cargo)||a.nomeCompleto.localeCompare(b.nomeCompleto)).map(u=>{let municipios:string[]=[];try{municipios=JSON.parse(u.municipiosAtendidosJson||"[]");}catch{}return <tr key={u.id} className="border-b"><td className="py-3 font-semibold">{u.nomeCompleto}</td><td>{u.email}</td><td>{u.cargo}</td><td>{u.associacao||"-"}</td><td>{municipios.join(", ")||"-"}</td><td>{u.mei||"-"}</td><td>{u.cftaCrea||"-"}</td><td className={u.documentoValidade<hoje?"font-bold text-red-700":""}>{u.documentoValidade}</td></tr>})}</tbody></table></div></section>}
    {aba==="acessos"&&<><UsuariosAcesso usuarios={acessos}/><SenhaAdmin/></>}
    {aba==="pendencias"&&<div className="mt-6 grid gap-6 lg:grid-cols-2"><Pendentes titulo="Sem Plano de Trabalho" usuarios={usuarios.filter(u=>!comPlano.has(u.authUserId))}/><Pendentes titulo="Sem Prestação de Contas" usuarios={usuarios.filter(u=>!comPrestacao.has(u.authUserId))}/></div>}
  </div></main>;
}

function Pendentes({titulo,usuarios}:{titulo:string;usuarios:Array<{id:number;nomeCompleto:string;cargo:string;associacao:string|null;email:string}>}){return <section className="rounded-2xl border border-amber-200 bg-amber-50 p-5"><h2 className="font-bold text-amber-950">{titulo}</h2><div className="mt-3 space-y-2">{usuarios.map(u=><div key={u.id} className="rounded-lg bg-white p-3 text-sm"><p className="font-semibold">{u.nomeCompleto}</p><p className="text-slate-500">{u.cargo} · {u.associacao||"Sem associação"} · {u.email}</p></div>)}{!usuarios.length&&<p className="text-sm text-emerald-800">Todos entregaram nesta competência.</p>}</div></section>}
