"use client";
import {useState} from "react";
import {MUNICIPIOS_ES} from "@/lib/municipios-es";
import {TIPOS_MUDAS} from "@/lib/opcoes-atividades";
import ExcluirEntregaButton from "./excluir-button";

type Dados={prestacaoId:number;atividadeIndex:number;data:string;municipio:string;tipoMuda:string;quantidadeMudas:string;observacao:string;retorno:string};
const campo="mt-1 h-11 w-full rounded-lg border bg-white px-3";
export default function EditarEntregaForm({dados}:{dados:Dados}){
 const[msg,setMsg]=useState("");const[salvando,setSalvando]=useState(false);const[quantidade,setQuantidade]=useState(dados.quantidadeMudas);
 async function salvar(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setSalvando(true);setMsg("");const f=new FormData(e.currentTarget);const r=await fetch("/api/admin/entrega-mudas/editar",{method:"POST",body:f});const b=await r.json().catch(()=>({}));setMsg(b.message||"NÃO FOI POSSÍVEL SALVAR.");setSalvando(false);if(r.ok)setTimeout(()=>location.href=dados.retorno,700);}
 return <form onSubmit={salvar} className="mt-6 grid gap-4 sm:grid-cols-2"><input type="hidden" name="prestacaoId" value={dados.prestacaoId}/><input type="hidden" name="atividadeIndex" value={dados.atividadeIndex}/><label className="text-sm font-bold">DATA DA ENTREGA<input name="data" type="date" defaultValue={dados.data} className={campo}/></label><label className="text-sm font-bold">MUNICÍPIO<select name="municipio" defaultValue={dados.municipio} className={campo}><option value="">NÃO INFORMADO</option>{dados.municipio&&!MUNICIPIOS_ES.includes(dados.municipio as typeof MUNICIPIOS_ES[number])&&<option>{dados.municipio}</option>}{MUNICIPIOS_ES.map(m=><option key={m}>{m}</option>)}</select></label><label className="text-sm font-bold">TIPO DE MUDA<select name="tipoMuda" defaultValue={dados.tipoMuda==="NÃO INFORMADO"?"":dados.tipoMuda} className={campo}><option value="">NÃO INFORMADO</option>{dados.tipoMuda&&dados.tipoMuda!=="NÃO INFORMADO"&&!TIPOS_MUDAS.includes(dados.tipoMuda as typeof TIPOS_MUDAS[number])&&<option>{dados.tipoMuda}</option>}{TIPOS_MUDAS.map(t=><option key={t}>{t}</option>)}</select></label><label className="text-sm font-bold">QUANTIDADE / TOTAL INFORMADO<input name="quantidade" type="number" min="0" step="1" value={quantidade} onChange={e=>setQuantidade(e.target.value)} className={campo}/><span className="mt-1 block text-xs text-slate-500">TOTAL RECALCULADO: {Number(quantidade||0).toLocaleString("pt-BR")} MUDA(S)</span></label><label className="text-sm font-bold sm:col-span-2">OBSERVAÇÃO<input name="observacao" defaultValue={dados.observacao} className={campo}/></label><ExcluirEntregaButton prestacaoId={dados.prestacaoId} atividadeIndex={dados.atividadeIndex} retorno={dados.retorno}/><button disabled={salvando} className="h-12 rounded-xl bg-emerald-800 font-black text-white disabled:opacity-50">{salvando?"SALVANDO...":"SALVAR ALTERAÇÕES"}</button>{msg&&<p className="rounded-xl bg-slate-100 p-4 text-sm font-bold sm:col-span-2">{msg}</p>}</form>;
}
