"use client";
import { useState } from "react";
import { MUNICIPIOS_ES } from "@/lib/municipios-es";
import { TIPOS_MUDAS } from "@/lib/opcoes-atividades";

export default function EntregaMudasForm({competenciaInicial,colaboradores}:{competenciaInicial:string;colaboradores:Array<{id:string;nome:string;associacao:string}>}){
  const [mensagem,setMensagem]=useState("");const [salvando,setSalvando]=useState(false);
  async function salvar(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setSalvando(true);setMensagem("");const resposta=await fetch("/api/admin/entrega-mudas",{method:"POST",body:new FormData(event.currentTarget)});const corpo=await resposta.json().catch(()=>({}));setMensagem(corpo.message||"NÃO FOI POSSÍVEL SALVAR.");if(resposta.ok)event.currentTarget.reset();setSalvando(false);}
  const campo="mt-1 block h-11 w-full rounded-lg border bg-white px-3";
  return <form onSubmit={salvar} className="mt-6 grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold">COMPETÊNCIA *<input name="competencia" type="month" defaultValue={competenciaInicial} required className={campo}/></label><label className="text-sm font-bold">COLABORADOR RESPONSÁVEL *<select name="authUserId" required className={campo}><option value="">SELECIONE</option>{colaboradores.map(item=><option key={item.id} value={item.id}>{item.nome} · {item.associacao||"SEM ASSOCIAÇÃO"}</option>)}</select></label><label className="text-sm font-bold">DATA DA ENTREGA *<input name="data" type="date" required className={campo}/></label><label className="text-sm font-bold">MUNICÍPIO *<select name="municipio" required className={campo}><option value="">SELECIONE</option>{MUNICIPIOS_ES.map(item=><option key={item}>{item}</option>)}</select></label><label className="text-sm font-bold">TIPO DE MUDAS *<select name="tipoMuda" required className={campo}><option value="">SELECIONE</option>{TIPOS_MUDAS.map(item=><option key={item}>{item}</option>)}</select></label><label className="text-sm font-bold">QUANTIDADE *<input name="quantidade" type="number" min="1" required className={campo}/></label><label className="text-sm font-bold sm:col-span-2">OBSERVAÇÃO<input name="observacao" className={campo}/></label><button disabled={salvando} className="h-12 rounded-xl bg-emerald-800 px-5 font-black text-white disabled:opacity-50 sm:col-span-2">{salvando?"SALVANDO...":"SALVAR ENTREGA DE MUDAS"}</button>{mensagem&&<p role="status" className="rounded-xl bg-slate-100 p-4 text-sm font-bold sm:col-span-2">{mensagem}</p>}</form>;
}
