"use client";
import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { AlertCircle, CheckCircle2, FileText, Loader2, Plus, Trash2, UploadCloud, Users } from "lucide-react";

type Cadastro = { nomeCompleto?: string | null; dataNascimento?: string | null; cpf?: string | null; sexo?: string | null; cargo?: string | null; associacao?: string | null; municipiosAtendidosJson?:string|null; mei?:string|null;cftaCrea?:string|null; cep?: string | null; endereco?: string | null; numero?: string | null; complemento?: string | null; bairro?: string | null; cidade?: string | null; uf?: string | null; celular?: string | null; atendimentosJson?: string | null; superioresJson?: string | null; documentoValidade?: string | null; };
type DocumentoNovo = { id: string; file: File; validade: string };
type Atendimento = { id: string; municipio: string; comunidade: string; propriedade: string; agricultor: string; telefone: string };
type Superiores = { agroindustria:string; projetos:string; associativismo:string; geral:string; mobilizador:string };
const superioresVazios:Superiores={agroindustria:"",projetos:"",associativismo:"",geral:"",mobilizador:""};
const atendimentoVazio=(id=crypto.randomUUID()):Atendimento=>({id,municipio:"",comunidade:"",propriedade:"",agricultor:"",telefone:""});
const cargos = ["Técnico de campo", "Mobilizador", "Consultor de agroindústria", "Consultor de projetos", "Consultor de associativismo", "Coordenador geral", "Subcoordenador", "Comunicação"];

export default function CadastroForm({ userEmail, initialData, associacoes }: { userEmail: string; initialData: Cadastro | null; associacoes:Array<{nome:string;municipios:string[]}> }) {
  const router = useRouter();
  const [status, setStatus] = useState<"idle" | "loading" | "success" | "error">("idle");
  const [message, setMessage] = useState("");
  const [documentos, setDocumentos] = useState<DocumentoNovo[]>([]);
  const [cargoSelecionado,setCargoSelecionado]=useState(initialData?.cargo||"");
  const [associacaoSelecionada,setAssociacaoSelecionada]=useState(initialData?.associacao||"");
  const [municipiosAtendidos,setMunicipiosAtendidos]=useState<string[]>(()=>{try{return JSON.parse(initialData?.municipiosAtendidosJson||"[]");}catch{return[];}});
  const [superiores,setSuperiores]=useState<Superiores>(()=>{try{return{...superioresVazios,...JSON.parse(initialData?.superioresJson||"{}")} as Superiores;}catch{return superioresVazios;}});
  const [atendimentos,setAtendimentos]=useState<Atendimento[]>(()=>{try{const salvos=JSON.parse(initialData?.atendimentosJson||"[]") as Array<Partial<Omit<Atendimento,"id">>>;return salvos.length?salvos.map((a,index)=>({id:`atendimento-${index}`,municipio:a.municipio||"",comunidade:a.comunidade||"",propriedade:a.propriedade||"",agricultor:a.agricultor||"",telefone:a.telefone||""})):[atendimentoVazio("atendimento-0")];}catch{return[atendimentoVazio("atendimento-0")];}});
  const validadeExpirada = useMemo(() => initialData?.documentoValidade ? new Date(initialData.documentoValidade + "T23:59:59") < new Date() : false, [initialData]);
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); if (!initialData && !documentos.length) { setStatus("error"); setMessage("Inclua pelo menos um documento."); return; } if (documentos.some(d => !d.validade)) { setStatus("error"); setMessage("Informe a validade de cada documento selecionado."); return; } if(cargoSelecionado==="Técnico de campo"&&!municipiosAtendidos.length){setStatus("error");setMessage("Selecione pelo menos um município atendido pelo técnico.");return;} if(atendimentos.some(a=>!a.municipio.trim()||!a.comunidade.trim()||!a.propriedade.trim()||!a.agricultor.trim()||!a.telefone.trim())){setStatus("error");setMessage("Complete município, comunidade, propriedade, agricultor e telefone em todos os atendimentos.");return;} setStatus("loading"); setMessage(""); const form = new FormData(event.currentTarget); form.set("municipiosAtendidos",JSON.stringify(cargoSelecionado==="Técnico de campo"?municipiosAtendidos:[])); form.set("atendimentos",JSON.stringify(atendimentos.map(({municipio,comunidade,propriedade,agricultor,telefone})=>({municipio,comunidade,propriedade,agricultor,telefone})))); form.set("superiores",JSON.stringify(cargoSelecionado==="Técnico de campo"?superiores:{})); form.delete("documentos"); documentos.forEach(d => { form.append("documentos", d.file); form.append("documentosValidades", d.validade); }); const response = await fetch("/api/cadastro", { method: "POST", body: form }); const body = await response.json().catch(() => ({})); setStatus(response.ok ? "success" : "error"); setMessage(body.message || (response.ok ? "Cadastro salvo com sucesso." : "Não foi possível salvar. Revise os campos e tente novamente.")); if (response.ok) setTimeout(() => router.push("/painel"), 700); }
  function incluirDocumentos(files: FileList | null) { if (!files) return; const novos = Array.from(files).map(file => ({ id: crypto.randomUUID(), file, validade: "" })); setDocumentos(atuais => [...atuais, ...novos]); }
  async function buscarCep(event: React.FocusEvent<HTMLInputElement>) { const cep = event.target.value.replace(/\D/g, ""); if (cep.length !== 8) return; try { const response = await fetch(`https://viacep.com.br/ws/${cep}/json/`); const data = await response.json(); if (!data.erro) { for (const [name, value] of Object.entries({ endereco: data.logradouro, bairro: data.bairro, cidade: data.localidade, uf: data.uf })) { const input = document.querySelector(`[name="${name}"]`) as HTMLInputElement | null; if (input) input.value = String(value || ""); } } } catch {} }
  const field = "mt-1.5 h-11 w-full rounded-lg border border-slate-300 bg-white px-3.5 text-base outline-none transition focus:border-emerald-700 focus:ring-4 focus:ring-emerald-700/10"; const label = "text-sm font-semibold text-slate-700";
  return <form onSubmit={submit} className="rounded-2xl border border-slate-200 bg-white shadow-sm"><nav className="flex flex-wrap gap-2 border-b border-slate-200 p-4" aria-label="Seções do cadastro"><a href="#dados" className="rounded-full bg-emerald-100 px-4 py-2 text-sm font-bold text-emerald-900">Dados do usuário</a>{cargoSelecionado==="Técnico de campo"&&<a href="#superiores" className="rounded-full bg-amber-100 px-4 py-2 text-sm font-bold text-amber-900">Superiores</a>}<a href="#atendimentos" className="rounded-full bg-blue-100 px-4 py-2 text-sm font-bold text-blue-900">Comunidades e agricultores</a><a href="#documentos" className="rounded-full bg-slate-100 px-4 py-2 text-sm font-bold text-slate-700">Documentos</a></nav>
    {validadeExpirada && <div className="m-5 flex gap-3 rounded-xl border border-amber-300 bg-amber-50 p-4 text-amber-950"><AlertCircle className="mt-0.5 h-5 w-5 shrink-0"/><div><p className="font-bold">Documento vencido</p><p className="text-sm">Envie um documento atualizado para continuar utilizando o portal.</p></div></div>}
    <div id="dados" className="grid scroll-mt-5 gap-5 p-5 sm:grid-cols-2 lg:p-7">
      <label className={`sm:col-span-2 ${label}`}>Nome completo *<input name="nomeCompleto" required defaultValue={initialData?.nomeCompleto ?? ""} className={field} placeholder="Digite o nome sem abreviações" /></label>
      <label className={label}>Data de nascimento *<input type="date" name="dataNascimento" required defaultValue={initialData?.dataNascimento ?? ""} className={field} /></label>
      <label className={label}>CPF *<input name="cpf" required inputMode="numeric" maxLength={14} defaultValue={initialData?.cpf ?? ""} className={field} placeholder="000.000.000-00" /></label>
      <label className={label}>Sexo *<select name="sexo" required defaultValue={initialData?.sexo ?? ""} className={field}><option value="" disabled>Selecione</option><option>Feminino</option><option>Masculino</option><option>Outro</option><option>Prefiro não informar</option></select></label>
      <label className={label}>Cargo *<select name="cargo" required value={cargoSelecionado} onChange={e=>setCargoSelecionado(e.target.value)} className={field}><option value="" disabled>Selecione</option>{cargos.map(c => <option key={c}>{c}</option>)}</select></label>
      <label className={`sm:col-span-2 ${label}`}>Associação *<select name="associacao" required value={associacaoSelecionada} onChange={e=>{setAssociacaoSelecionada(e.target.value);setMunicipiosAtendidos([]);}} className={field}><option value="" disabled>Selecione a associação</option>{associacoes.map(a => <option key={a.nome}>{a.nome}</option>)}</select></label>
      {cargoSelecionado==="Técnico de campo"&&<div className={`sm:col-span-2 ${label}`}><span>Municípios atendidos pelo técnico *</span><div className="mt-2 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{(associacoes.find(a=>a.nome===associacaoSelecionada)?.municipios||[]).map(m=><label key={m} className="flex items-center gap-2 rounded-lg border bg-slate-50 p-3 font-normal"><input type="checkbox" checked={municipiosAtendidos.includes(m)} onChange={e=>setMunicipiosAtendidos(xs=>e.target.checked?[...xs,m]:xs.filter(x=>x!==m))}/>{m}</label>)}</div>{associacaoSelecionada&&!(associacoes.find(a=>a.nome===associacaoSelecionada)?.municipios.length)&&<p className="mt-2 rounded-lg bg-amber-50 p-3 text-sm font-normal text-amber-900">A administração ainda precisa cadastrar os municípios atendidos por esta associação.</p>}</div>}
      <label className={label}>MEI<input name="mei" defaultValue={initialData?.mei??""} className={field} placeholder="Número ou identificação do MEI"/></label>
      <label className={label}>CFTA/CREA<input name="cftaCrea" defaultValue={initialData?.cftaCrea??""} className={field} placeholder="Registro profissional"/></label>
      <label className={label}>CEP *<input name="cep" required inputMode="numeric" onBlur={buscarCep} defaultValue={initialData?.cep ?? ""} className={field} placeholder="00000-000" /></label>
      <label className={label}>Endereço *<input name="endereco" required defaultValue={initialData?.endereco ?? ""} className={field} placeholder="Rua, avenida ou comunidade" /></label>
      <label className={label}>Número *<input name="numero" required defaultValue={initialData?.numero ?? ""} className={field} /></label>
      <label className={label}>Complemento<input name="complemento" defaultValue={initialData?.complemento ?? ""} className={field} /></label>
      <label className={label}>Bairro ou comunidade *<input name="bairro" required defaultValue={initialData?.bairro ?? ""} className={field} /></label>
      <label className={label}>Município *<input name="cidade" required defaultValue={initialData?.cidade ?? ""} className={field} /></label>
      <label className={label}>UF *<input name="uf" required maxLength={2} defaultValue={initialData?.uf ?? "ES"} className={field} /></label>
      <label className={label}>Celular *<input type="tel" name="celular" required defaultValue={initialData?.celular ?? ""} className={field} placeholder="(27) 99999-9999" /></label>
      <label className={`sm:col-span-2 ${label}`}>E-mail de acesso<input name="email" value={userEmail} readOnly className={`${field} bg-slate-100 text-slate-600`} /><span className="mt-1.5 block text-xs font-normal text-slate-500">Este e-mail identifica o usuário no login e não pode ser alterado neste formulário.</span></label>
    </div>
    {cargoSelecionado==="Técnico de campo"&&<div id="superiores" className="scroll-mt-5 border-t border-amber-200 bg-amber-50/50 p-5 lg:p-7"><div className="mb-4 flex items-center gap-3"><Users className="h-5 w-5 text-amber-800"/><div><h3 className="font-bold">Identificação dos superiores</h3><p className="text-sm text-slate-600">Informe os nomes dos responsáveis que acompanham o técnico de campo.</p></div></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><label className={label}>Consultor de agroindústria<input value={superiores.agroindustria} onChange={e=>setSuperiores(s=>({...s,agroindustria:e.target.value}))} className={field}/></label><label className={label}>Consultor de projetos<input value={superiores.projetos} onChange={e=>setSuperiores(s=>({...s,projetos:e.target.value}))} className={field}/></label><label className={label}>Consultor de associativismo<input value={superiores.associativismo} onChange={e=>setSuperiores(s=>({...s,associativismo:e.target.value}))} className={field}/></label><label className={label}>Consultor geral<input value={superiores.geral} onChange={e=>setSuperiores(s=>({...s,geral:e.target.value}))} className={field}/></label><label className={label}>Mobilizador<input value={superiores.mobilizador} onChange={e=>setSuperiores(s=>({...s,mobilizador:e.target.value}))} className={field}/></label></div></div>}
    <div id="atendimentos" className="scroll-mt-5 border-t border-slate-200 bg-blue-50/40 p-5 lg:p-7"><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-3"><Users className="h-5 w-5 text-blue-800"/><div><h3 className="font-bold">Comunidades, propriedades e agricultores atendidos</h3><p className="text-sm text-slate-600">Cadastre todos os dados para o preenchimento automático do plano e da prestação.</p></div></div><button type="button" onClick={()=>setAtendimentos(xs=>[...xs,atendimentoVazio()])} className="inline-flex h-10 items-center gap-2 rounded-lg border border-blue-700 bg-white px-4 text-sm font-bold text-blue-800"><Plus className="h-4 w-4"/>Adicionar atendimento</button></div><div className="space-y-3">{atendimentos.map((a,index)=><div key={a.id} className="grid gap-3 rounded-xl border border-blue-200 bg-white p-4 sm:grid-cols-2 lg:grid-cols-[1fr_1fr_1fr_1fr_1fr_auto] lg:items-end"><label className={label}>Município *<input required value={a.municipio} onChange={e=>setAtendimentos(xs=>xs.map(x=>x.id===a.id?{...x,municipio:e.target.value}:x))} className={field}/></label><label className={label}>Comunidade *<input required value={a.comunidade} onChange={e=>setAtendimentos(xs=>xs.map(x=>x.id===a.id?{...x,comunidade:e.target.value}:x))} className={field}/></label><label className={label}>Propriedade *<input required value={a.propriedade} onChange={e=>setAtendimentos(xs=>xs.map(x=>x.id===a.id?{...x,propriedade:e.target.value}:x))} className={field}/></label><label className={label}>Agricultor *<input required value={a.agricultor} onChange={e=>setAtendimentos(xs=>xs.map(x=>x.id===a.id?{...x,agricultor:e.target.value}:x))} className={field}/></label><label className={label}>Telefone *<input type="tel" required value={a.telefone} onChange={e=>setAtendimentos(xs=>xs.map(x=>x.id===a.id?{...x,telefone:e.target.value}:x))} className={field}/></label><button type="button" disabled={atendimentos.length===1} aria-label={`Remover atendimento ${index+1}`} onClick={()=>setAtendimentos(xs=>xs.filter(x=>x.id!==a.id))} className="inline-flex h-11 items-center justify-center rounded-lg border border-red-200 px-3 text-red-700 disabled:opacity-30"><Trash2 className="h-4 w-4"/></button></div>)}</div></div>
    <div id="documentos" className="scroll-mt-5 border-t border-slate-200 bg-slate-50/70 p-5 lg:p-7">
      <div className="mb-4 flex items-center gap-3"><FileText className="h-5 w-5 text-emerald-800"/><div><h3 className="font-bold">Documentos de identificação</h3><p className="text-sm text-slate-600">Adicione um arquivo por vez ou selecione vários de uma só vez. Cada documento terá sua própria validade.</p></div></div>
      <label className="flex min-h-28 cursor-pointer flex-col items-center justify-center rounded-xl border-2 border-dashed border-slate-300 bg-white p-5 text-center hover:border-emerald-700 hover:bg-emerald-50/40"><UploadCloud className="h-7 w-7 text-emerald-800"/><span className="mt-2 text-sm font-bold">Adicionar documento(s)</span><span className="mt-1 text-xs text-slate-500">PDF, JPG ou PNG — até 10 MB por arquivo</span><input type="file" multiple accept=".pdf,.jpg,.jpeg,.png" className="sr-only" onChange={e=>{incluirDocumentos(e.target.files);e.target.value="";}} /></label>
      {initialData && !documentos.length && <p className="mt-3 rounded-lg bg-emerald-50 p-3 text-sm text-emerald-800">Os documentos já cadastrados serão mantidos. Use o botão acima para acrescentar novos arquivos.</p>}
      <div className="mt-4 space-y-3">{documentos.map((doc,index)=><div key={doc.id} className="grid gap-3 rounded-xl border bg-white p-4 sm:grid-cols-[1fr_210px_auto] sm:items-end"><div className="min-w-0"><p className="text-xs font-bold uppercase tracking-wide text-slate-500">Documento {index+1}</p><p className="truncate font-semibold">{doc.file.name}</p><p className="text-xs text-slate-500">{(doc.file.size/1024/1024).toFixed(2)} MB</p></div><label className={label}>Validade *<input type="date" required value={doc.validade} onChange={e=>setDocumentos(ds=>ds.map(d=>d.id===doc.id?{...d,validade:e.target.value}:d))} className={field}/></label><button type="button" onClick={()=>setDocumentos(ds=>ds.filter(d=>d.id!==doc.id))} className="h-11 rounded-lg border border-red-200 px-4 font-semibold text-red-700 hover:bg-red-50">Remover</button></div>)}</div>
    </div>
    <div className="flex flex-col-reverse items-stretch justify-between gap-4 border-t border-slate-200 p-5 sm:flex-row sm:items-center lg:p-7"><div aria-live="polite" className="min-h-6 text-sm">{status === "success" && <span className="flex items-center gap-2 font-semibold text-emerald-700"><CheckCircle2 className="h-5 w-5"/>{message}</span>}{status === "error" && <span className="flex items-center gap-2 font-semibold text-red-700"><AlertCircle className="h-5 w-5"/>{message}</span>}</div><button disabled={status === "loading"} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-lg bg-[#176344] px-6 py-3 font-bold text-white shadow-sm hover:bg-[#124f37] disabled:opacity-60">{status === "loading" && <Loader2 className="h-4 w-4 animate-spin"/>}{initialData ? "Atualizar cadastro" : "Salvar e continuar"}</button></div>
  </form>;
}
