import { ArrowRight, Building2, ClipboardCheck, LockKeyhole, ShieldCheck, UserPlus } from "lucide-react";
import { chatGPTSignInPath, getChatGPTUser } from "./chatgpt-auth";

export const dynamic = "force-dynamic";

export default async function Home() {
  const user = await getChatGPTUser();
  const entrar = user ? "/painel" : chatGPTSignInPath("/painel");
  const cadastrar = user ? "/cadastro" : "/criar-conta";
  const administrar = user ? "/admin" : chatGPTSignInPath("/admin");
  const portalAssociacao = "/entrar-associacao";
  return <main className="min-h-screen bg-[#f2f6f1] text-slate-900">
    <header className="bg-[#123b2a] text-white"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-5 lg:px-8"><div className="flex items-center gap-3"><span className="grid h-12 w-12 place-items-center rounded-xl bg-[#e6b44a] text-xl font-black text-[#123b2a]">AP</span><div><p className="font-bold tracking-wide">ARRANJOS PRODUTIVOS</p><p className="text-sm text-emerald-100">Prestação de contas 2026</p></div></div><span className="hidden rounded-full border border-white/15 bg-white/5 px-4 py-2 text-sm text-emerald-50 sm:inline-flex">Ambiente seguro</span></div></header>
    <section className="relative overflow-hidden bg-[#123b2a] pb-28 pt-12 text-white sm:pt-16"><div className="absolute inset-x-0 bottom-0 h-24 bg-[#f2f6f1] [clip-path:polygon(0_78%,100%_0,100%_100%,0_100%)]"/><div className="relative mx-auto max-w-3xl px-5 text-center"><div className="mx-auto mb-5 grid h-14 w-14 place-items-center rounded-2xl bg-white/10"><ClipboardCheck className="h-7 w-7 text-[#e6b44a]"/></div><h1 className="text-3xl font-bold tracking-tight sm:text-4xl">Portal de Prestação de Contas</h1><p className="mx-auto mt-4 max-w-2xl text-base leading-7 text-emerald-100 sm:text-lg">Acesse seu ambiente para manter o cadastro, documentos e atividades do Projeto Arranjos Produtivos atualizados.</p></div></section>
    <section className="relative mx-auto -mt-10 max-w-6xl px-5 pb-12 lg:px-8"><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-4">
      <article className="group rounded-2xl border border-slate-200 bg-white p-6 shadow-[0_12px_40px_rgba(18,59,42,.08)] sm:p-8"><span className="grid h-12 w-12 place-items-center rounded-xl bg-emerald-100 text-emerald-800"><LockKeyhole className="h-6 w-6"/></span><p className="mt-6 text-sm font-bold uppercase tracking-[.14em] text-emerald-700">Já sou cadastrado</p><h2 className="mt-2 text-2xl font-bold">Entrar no portal</h2><p className="mt-3 min-h-12 leading-6 text-slate-600">Use seu e-mail de acesso para consultar e atualizar suas informações.</p><a href={entrar} target={user?undefined:"_top"} className="mt-7 inline-flex min-h-12 w-full items-center justify-center gap-2 rounded-xl bg-[#176344] px-5 font-bold text-white transition hover:bg-[#124f37]">Entrar <ArrowRight className="h-4 w-4"/></a></article>
      <article className="group rounded-2xl border border-[#e6b44a]/50 bg-white p-6 shadow-[0_12px_40px_rgba(18,59,42,.08)] sm:p-8"><span className="grid h-12 w-12 place-items-center rounded-xl bg-amber-100 text-amber-800"><UserPlus className="h-6 w-6"/></span><p className="mt-6 text-sm font-bold uppercase tracking-[.14em] text-amber-700">Primeiro acesso</p><h2 className="mt-2 text-2xl font-bold">Criar cadastro</h2><p className="mt-3 min-h-12 leading-6 text-slate-600">Cadastre seus dados pessoais, função, contato e documento de identificação.</p><a href={cadastrar} target={user?undefined:"_top"} className="mt-7 inline-flex min-h-12 w-full items-center justify-center gap-2 rounded-xl border-2 border-[#176344] px-5 font-bold text-[#176344] transition hover:bg-emerald-50">Fazer cadastro <ArrowRight className="h-4 w-4"/></a></article>
      <article className="group rounded-2xl border border-blue-200 bg-white p-6 shadow-[0_12px_40px_rgba(18,59,42,.08)] sm:p-8"><span className="grid h-12 w-12 place-items-center rounded-xl bg-blue-100 text-blue-800"><ShieldCheck className="h-6 w-6"/></span><p className="mt-6 text-sm font-bold uppercase tracking-[.14em] text-blue-700">Gestão</p><h2 className="mt-2 text-2xl font-bold">Área administrativa</h2><p className="mt-3 min-h-12 leading-6 text-slate-600">Acompanhe usuários, planos, prestações, pendências e associações.</p><a href={administrar} target={user?undefined:"_top"} className="mt-7 inline-flex min-h-12 w-full items-center justify-center gap-2 rounded-xl bg-blue-800 px-5 font-bold text-white transition hover:bg-blue-900">Login administrativo <ArrowRight className="h-4 w-4"/></a></article>
      <article className="group rounded-2xl border border-violet-200 bg-white p-6 shadow-[0_12px_40px_rgba(18,59,42,.08)] sm:p-8"><span className="grid h-12 w-12 place-items-center rounded-xl bg-violet-100 text-violet-800"><Building2 className="h-6 w-6"/></span><p className="mt-6 text-sm font-bold uppercase tracking-[.14em] text-violet-700">Associações</p><h2 className="mt-2 text-2xl font-bold">Documentos financeiros</h2><p className="mt-3 min-h-12 leading-6 text-slate-600">Envie extratos bancários e notas fiscais por competência.</p><a href={portalAssociacao} target="_top" className="mt-7 inline-flex min-h-12 w-full items-center justify-center gap-2 rounded-xl bg-violet-800 px-5 font-bold text-white transition hover:bg-violet-900">Acesso da associação <ArrowRight className="h-4 w-4"/></a></article>
    </div><div className="mt-6 flex items-start justify-center gap-2 text-center text-sm text-slate-500"><LockKeyhole className="mt-0.5 h-4 w-4 shrink-0"/><p>O e-mail é utilizado como identificação do usuário. Seus dados e documentos ficam protegidos.</p></div></section>
  </main>;
}
