"use client";
import {useState} from "react";
import {FileText, Loader2, UploadCloud} from "lucide-react";

export default function DocumentosAssociacaoForm({associacao}:{associacao:string}){
 const[extratos,setExtratos]=useState<File[]>([]);const[notas,setNotas]=useState<File[]>([]);const[msg,setMsg]=useState("");const[loading,setLoading]=useState(false);
 const campo="mt-1.5 h-12 w-full rounded-xl border border-slate-300 bg-white px-4 text-base";
 async function enviar(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!extratos.length||!notas.length){setMsg("INCLUA PELO MENOS UM EXTRATO BANCÁRIO E UMA NOTA FISCAL.");return;}setLoading(true);setMsg("");const f=new FormData(e.currentTarget);extratos.forEach(a=>f.append("extratos",a));notas.forEach(a=>f.append("notasFiscais",a));const r=await fetch("/api/associacao/documentos",{method:"POST",body:f});const b=await r.json().catch(()=>({}));setMsg(b.message||"NÃO FOI POSSÍVEL SALVAR.");setLoading(false);if(r.ok)setTimeout(()=>location.reload(),700);}
 function seletor(titulo:string,arquivos:File[],alterar:(f:File[])=>void,nome:string){return <div className="rounded-xl border border-slate-200 p-4"><div className="flex items-center gap-2"><FileText className="h-5 w-5 text-emerald-700"/><h3 className="font-bold">{titulo} *</h3></div><label className="mt-3 flex min-h-28 cursor-pointer flex-col items-center justify-center rounded-xl border-2 border-dashed border-slate-300 bg-slate-50 p-4 text-center"><UploadCloud className="h-7 w-7 text-emerald-700"/><span className="mt-2 font-bold">SELECIONAR UM OU VÁRIOS ARQUIVOS</span><span className="text-xs text-slate-500">PDF, JPG OU PNG — ATÉ 10 MB POR ARQUIVO</span><input name={nome} type="file" multiple accept=".pdf,.jpg,.jpeg,.png" className="sr-only" onChange={e=>{alterar([...arquivos,...Array.from(e.target.files||[])]);e.target.value=""}}/></label><div className="mt-3 space-y-2">{arquivos.map((a,i)=><div key={`${a.name}-${i}`} className="flex items-center justify-between gap-3 rounded-lg bg-slate-100 px-3 py-2 text-sm"><span className="min-w-0 truncate font-semibold">{a.name}</span><button type="button" onClick={()=>alterar(arquivos.filter((_,x)=>x!==i))} className="font-bold text-red-700">REMOVER</button></div>)}</div></div>}
 return <section className="rounded-2xl border bg-white p-5 shadow-sm sm:p-7"><p className="text-sm font-bold text-emerald-700">PRESTAÇÃO DE CONTAS DA ASSOCIAÇÃO</p><h1 className="mt-1 text-3xl font-bold">ENVIO DE DOCUMENTOS</h1><p className="mt-2 text-slate-600">{associacao}</p><form onSubmit={enviar} className="mt-6"><input type="hidden" name="associacao" value={associacao}/><label className="block text-sm font-bold">MÊS DE COMPETÊNCIA *<input type="month" name="competencia" required className={campo}/></label><div className="mt-5 grid gap-5 lg:grid-cols-2">{seletor("EXTRATOS BANCÁRIOS",extratos,setExtratos,"extratosInput")}{seletor("NOTAS FISCAIS",notas,setNotas,"notasInput")}</div><button disabled={loading} className="mt-5 inline-flex min-h-12 w-full items-center justify-center gap-2 rounded-xl bg-emerald-700 px-5 font-bold text-white disabled:opacity-50">{loading&&<Loader2 className="h-4 w-4 animate-spin"/>}SALVAR DOCUMENTOS</button>{msg&&<p className="mt-4 rounded-lg bg-slate-100 p-3 text-sm font-bold">{msg}</p>}</form></section>;
}
