"use client";
import {useState} from "react";
import {Loader2,Trash2} from "lucide-react";

type Arquivo={key:string;nome:string;tipo:string};
type Envio={id:number;competencia:string;associacao:string;extratos:Arquivo[];notas:Arquivo[];atualizadoEm:string};

export default function EnviosClient({envios,associacoes,superAdmin}:{envios:Envio[];associacoes:string[];superAdmin:boolean}){
 const[processando,setProcessando]=useState("");const[msg,setMsg]=useState("");
 async function excluir(id:number,categoria:string,arquivo:Arquivo){if(!confirm(`EXCLUIR O ARQUIVO ${arquivo.nome}?`))return;const chave=`excluir-${arquivo.key}`;setProcessando(chave);setMsg("");const r=await fetch("/api/associacao/documentos",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({id,categoria,key:arquivo.key})});const b=await r.json().catch(()=>({}));setMsg(b.message||"NÃO FOI POSSÍVEL EXCLUIR.");setProcessando("");if(r.ok)setTimeout(()=>location.reload(),500);}
 async function alterar(id:number,categoria:string,arquivo:Arquivo,associacao:string){if(!associacao)return;const chave=`alterar-${arquivo.key}`;setProcessando(chave);setMsg("");const r=await fetch("/api/associacao/documentos",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,categoria,key:arquivo.key,associacao})});const b=await r.json().catch(()=>({}));setMsg(b.message||"NÃO FOI POSSÍVEL ALTERAR.");setProcessando("");if(r.ok)setTimeout(()=>location.reload(),500);}
 function lista(envio:Envio,categoria:"extrato"|"nota",arquivos:Arquivo[]){return <div className="space-y-2">{arquivos.map(arquivo=><div key={arquivo.key} className="rounded-lg border bg-slate-50 p-3"><p className="break-all font-semibold">{arquivo.nome}</p><div className="mt-2 flex flex-wrap gap-2">{superAdmin&&<><select id={`assoc-${arquivo.key}`} defaultValue="" className="h-9 min-w-48 rounded-lg border bg-white px-2 text-xs"><option value="">ALTERAR ASSOCIAÇÃO</option>{associacoes.filter(a=>a!==envio.associacao).map(a=><option key={a} value={a}>{a}</option>)}</select><button type="button" disabled={!!processando} onClick={()=>{const el=document.getElementById(`assoc-${arquivo.key}`) as HTMLSelectElement;alterar(envio.id,categoria,arquivo,el.value)}} className="rounded-lg bg-blue-800 px-3 text-xs font-bold text-white">ALTERAR</button></>}<button type="button" disabled={!!processando} onClick={()=>excluir(envio.id,categoria,arquivo)} className="inline-flex h-9 items-center gap-1 rounded-lg bg-red-700 px-3 text-xs font-bold text-white"><Trash2 className="h-4 w-4"/>EXCLUIR</button>{processando.endsWith(arquivo.key)&&<Loader2 className="h-5 w-5 animate-spin"/>}</div></div>)}</div>}
 return <section className="mt-6 rounded-2xl border bg-white p-5 shadow-sm"><h2 className="text-xl font-bold">ENVIOS REALIZADOS</h2>{msg&&<p className="mt-3 rounded-lg bg-slate-100 p-3 text-sm font-bold">{msg}</p>}<div className="mt-4 space-y-5">{envios.map(envio=><article key={envio.id} className="rounded-xl border p-4"><div className="flex flex-wrap items-center justify-between gap-2 border-b pb-3"><div><h3 className="text-lg font-black">{envio.competencia}</h3><p className="text-sm text-slate-500">{envio.associacao} · ATUALIZADO EM {envio.atualizadoEm}</p></div></div><div className="mt-4 grid gap-5 lg:grid-cols-2"><div><h4 className="mb-2 font-bold text-emerald-800">EXTRATOS BANCÁRIOS ({envio.extratos.length})</h4>{lista(envio,"extrato",envio.extratos)}{!envio.extratos.length&&<p className="text-sm text-slate-500">NENHUM ARQUIVO.</p>}</div><div><h4 className="mb-2 font-bold text-emerald-800">NOTAS FISCAIS ({envio.notas.length})</h4>{lista(envio,"nota",envio.notas)}{!envio.notas.length&&<p className="text-sm text-slate-500">NENHUM ARQUIVO.</p>}</div></div></article>)}{!envios.length&&<p className="py-8 text-center text-slate-500">NENHUM DOCUMENTO ENVIADO.</p>}</div></section>;
}
