"use client";
import {useState} from "react";
import {Plus,Trash2} from "lucide-react";
import {CARGOS_EQUIPE,CULTURAS_PLANO,ETAPAS_PLANO,ITENS_APLICACAO,OBJETIVOS_MONITORAMENTO} from "@/lib/plano-associacao";

type Linha=Record<string,string>;
const campo="mt-1 h-11 w-full rounded-lg border bg-white px-3 text-sm";
const area="mt-1 min-h-24 w-full rounded-lg border bg-white p-3 text-sm";
const copia=<T extends readonly object[]>(itens:T)=>itens.map(item=>({...item})) as Linha[];
function numero(valor:string){return Number(valor.replace(/\./g,"").replace(",","."))||0;}
function quantidadeFormatada(valor:string){const digitos=valor.replace(/\D/g,"");return digitos?Number(digitos).toLocaleString("pt-BR"):"";}
function valorFormatado(valor:number){return valor.toLocaleString("pt-BR",{minimumFractionDigits:2,maximumFractionDigits:2});}
function itemPreparado(item:object){const linha={...item} as Linha;linha.quantidade=quantidadeFormatada(linha.quantidade||"");linha.valorTotal=valorFormatado(numero(linha.quantidade)*numero(linha.valorUnitario));return linha;}

export default function PlanoAssociacaoForm({associacao}:{associacao:{id:number;nome:string;razaoSocial:string;municipiosJson:string}}){
 let municipios:string[]=[];try{municipios=JSON.parse(associacao.municipiosJson||"[]");}catch{}
 const[culturas,setCulturas]=useState<string[]>([]);const[inicio,setInicio]=useState("MARÇO DE 2026");const[termino,setTermino]=useState("MARÇO DE 2027");
 const[etapas,setEtapas]=useState<Linha[]>(copia(ETAPAS_PLANO));const[objetivos,setObjetivos]=useState<Linha[]>(copia(OBJETIVOS_MONITORAMENTO));const[equipe,setEquipe]=useState<Linha[]>(copia(CARGOS_EQUIPE.slice(0,4)));const[itens,setItens]=useState<Linha[]>(ITENS_APLICACAO.map(itemPreparado));
 const[repasses,setRepasses]=useState([{mes:"MARÇO/2026",valor:"365386,00"},{mes:"ABRIL/2026",valor:"365386,00"}]);const[gerando,setGerando]=useState(false);const[msg,setMsg]=useState("");
 function trocarPreset(lista:Linha[],setLista:(v:Linha[])=>void,indice:number,preset:object){const nova=[...lista];nova[indice]={...preset} as Linha;setLista(nova)}
 function alterar(lista:Linha[],setLista:(v:Linha[])=>void,indice:number,chave:string,valor:string){const nova=[...lista];nova[indice]={...nova[indice],[chave]:valor};setLista(nova)}
 function adicionar(setLista:(v:Linha[])=>void,lista:Linha[],preset:object){setLista([...lista,{...preset} as Linha])}
 function excluir(setLista:(v:Linha[])=>void,lista:Linha[],indice:number){setLista(lista.filter((_,i)=>i!==indice))}
 function alterarItem(indice:number,chave:string,valor:string){const nova=[...itens];const atual={...nova[indice],[chave]:chave==="quantidade"?quantidadeFormatada(valor):valor};if(chave==="quantidade"||chave==="valorUnitario")atual.valorTotal=valorFormatado(numero(atual.quantidade)*numero(atual.valorUnitario));nova[indice]=atual;setItens(nova)}
 async function gerar(){setGerando(true);setMsg("");try{const resposta=await fetch("/api/admin/associacoes/plano-trabalho",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({associacaoId:associacao.id,inicio,termino,culturas,etapas,objetivos,equipe,itens,repasses})});if(!resposta.ok){const erro=await resposta.json().catch(()=>({}));throw new Error(erro.message||"NÃO FOI POSSÍVEL GERAR O PLANO.")}const blob=await resposta.blob();const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`PLANO_DE_TRABALHO_${associacao.nome.replace(/\W+/g,"_")}.docx`;a.click();URL.revokeObjectURL(url);setMsg("PLANO DE TRABALHO GERADO COM SUCESSO.");}catch(e){setMsg(e instanceof Error?e.message:"NÃO FOI POSSÍVEL GERAR.")}finally{setGerando(false)}}
 return <div className="mt-6 space-y-7">
  <section className="grid gap-4 rounded-xl border bg-slate-50 p-5 sm:grid-cols-2"><div className="sm:col-span-2"><p className="font-black text-emerald-900">{associacao.razaoSocial}</p><p className="text-sm text-slate-600">MUNICÍPIOS ATENDIDOS: {municipios.join(" · ")||"NÃO CADASTRADOS"}</p></div><label className="text-sm font-bold">INÍCIO DO PERÍODO<input value={inicio} onChange={e=>setInicio(e.target.value)} className={campo}/></label><label className="text-sm font-bold">TÉRMINO DO PERÍODO<input value={termino} onChange={e=>setTermino(e.target.value)} className={campo}/></label><fieldset className="sm:col-span-2"><legend className="text-sm font-bold">CULTURAS DA ASSOCIAÇÃO</legend><div className="mt-2 grid gap-2 sm:grid-cols-3 lg:grid-cols-4">{CULTURAS_PLANO.map(c=><label key={c} className="flex items-center gap-2 rounded-lg border bg-white p-2 text-sm"><input type="checkbox" checked={culturas.includes(c)} onChange={()=>setCulturas(x=>x.includes(c)?x.filter(v=>v!==c):[...x,c])}/>{c}</label>)}</div></fieldset></section>
  <Bloco titulo="DETALHAMENTO METODOLÓGICO" subtitulo="AO ESCOLHER A ETAPA, OS DEMAIS CAMPOS SÃO PREENCHIDOS AUTOMATICAMENTE.">{etapas.map((l,i)=><div key={i} className="grid min-w-0 gap-3 rounded-xl border p-4 lg:grid-cols-2"><BarraLinha titulo={`ETAPA ${i+1}`} excluir={()=>excluir(setEtapas,etapas,i)}/><label className="min-w-0 text-sm font-bold">ETAPA<select value={l.nome} onChange={e=>trocarPreset(etapas,setEtapas,i,ETAPAS_PLANO.find(x=>x.nome===e.target.value)||ETAPAS_PLANO[0])} className={campo}>{ETAPAS_PLANO.map(x=><option key={x.nome}>{x.nome}</option>)}</select></label><CampoArea titulo="OBJETIVO ESPECÍFICO" valor={l.objetivo} mudar={v=>alterar(etapas,setEtapas,i,"objetivo",v)}/><CampoArea titulo="AÇÕES" valor={l.acoes} mudar={v=>alterar(etapas,setEtapas,i,"acoes",v)}/><CampoArea titulo="METAS" valor={l.metas} mudar={v=>alterar(etapas,setEtapas,i,"metas",v)}/><CampoArea titulo="RESULTADOS ESPERADOS" valor={l.resultados} mudar={v=>alterar(etapas,setEtapas,i,"resultados",v)}/></div>)}<BotaoAdicionar texto="INCLUIR ETAPA" clicar={()=>adicionar(setEtapas,etapas,ETAPAS_PLANO[0])}/></Bloco>
  <Bloco titulo="MATRIZ DE MONITORAMENTO E AVALIAÇÃO" subtitulo="AO ESCOLHER O OBJETIVO, OS INDICADORES E DEMAIS CAMPOS SÃO PREENCHIDOS.">{objetivos.map((l,i)=><div key={i} className="grid min-w-0 gap-3 rounded-xl border p-4 lg:grid-cols-2"><BarraLinha titulo={`OBJETIVO ${i+1}`} excluir={()=>excluir(setObjetivos,objetivos,i)}/><label className="min-w-0 text-sm font-bold lg:col-span-2">OBJETIVO ESPECÍFICO<select value={l.objetivo} onChange={e=>trocarPreset(objetivos,setObjetivos,i,OBJETIVOS_MONITORAMENTO.find(x=>x.objetivo===e.target.value)||OBJETIVOS_MONITORAMENTO[0])} className={campo}>{OBJETIVOS_MONITORAMENTO.map(x=><option key={x.objetivo}>{x.objetivo}</option>)}</select></label>{["quantitativos","qualitativos","fonte","coleta","responsavel","periodicidade"].map(k=><CampoArea key={k} titulo={k.toUpperCase()} valor={l[k]} mudar={v=>alterar(objetivos,setObjetivos,i,k,v)}/>)}</div>)}<BotaoAdicionar texto="INCLUIR OBJETIVO" clicar={()=>adicionar(setObjetivos,objetivos,OBJETIVOS_MONITORAMENTO[0])}/></Bloco>
  <Bloco titulo="EQUIPE TÉCNICA" subtitulo="O CARGO PREENCHE AS ATRIBUIÇÕES. NÚMERO DE PROFISSIONAIS E ESCOLARIDADE PERMANECEM EDITÁVEIS.">{equipe.map((l,i)=><div key={i} className="grid min-w-0 gap-3 rounded-xl border p-4 sm:grid-cols-2 lg:grid-cols-4"><BarraLinha titulo={`PROFISSIONAL / CARGO ${i+1}`} excluir={()=>excluir(setEquipe,equipe,i)}/><label className="min-w-0 text-sm font-bold sm:col-span-2">CARGO<select value={l.cargo} onChange={e=>trocarPreset(equipe,setEquipe,i,CARGOS_EQUIPE.find(x=>x.cargo===e.target.value)||CARGOS_EQUIPE[0])} className={campo}>{CARGOS_EQUIPE.map(x=><option key={x.cargo}>{x.cargo}</option>)}</select></label>{["numero","escolaridade","periodo","natureza"].map(k=><label key={k} className="min-w-0 text-sm font-bold">{k.toUpperCase()}<input value={l[k]} onChange={e=>alterar(equipe,setEquipe,i,k,e.target.value)} className={campo}/></label>)}<div className="sm:col-span-2 lg:col-span-4"><CampoArea titulo="ATRIBUIÇÕES" valor={l.atribuicoes} mudar={v=>alterar(equipe,setEquipe,i,"atribuicoes",v)}/></div></div>)}<BotaoAdicionar texto="INCLUIR PROFISSIONAL / CARGO" clicar={()=>adicionar(setEquipe,equipe,CARGOS_EQUIPE[0])}/></Bloco>
  <Bloco titulo="CRONOGRAMA DE DESEMBOLSO DO REPASSE" subtitulo="MESES E VALORES EDITÁVEIS."><div className="grid gap-3 sm:grid-cols-2">{repasses.map((r,i)=><div key={i} className="grid min-w-0 grid-cols-2 gap-3 rounded-xl border p-4"><BarraLinha titulo={`REPASSE ${i+1}`} excluir={()=>setRepasses(repasses.filter((_,x)=>x!==i))}/><label className="min-w-0 text-sm font-bold">MÊS<input value={r.mes} onChange={e=>{const n=[...repasses];n[i]={...r,mes:e.target.value};setRepasses(n)}} className={campo}/></label><label className="min-w-0 text-sm font-bold">VALOR (R$)<input value={r.valor} onChange={e=>{const n=[...repasses];n[i]={...r,valor:e.target.value};setRepasses(n)}} className={campo}/></label></div>)}</div><BotaoAdicionar texto="INCLUIR REPASSE" clicar={()=>setRepasses([...repasses,{mes:"",valor:""}])}/></Bloco>
  <Bloco titulo="PLANO DE APLICAÇÃO DE RECURSOS" subtitulo="A QUANTIDADE SERÁ MULTIPLICADA PELO VALOR UNITÁRIO PARA CALCULAR AUTOMATICAMENTE O VALOR TOTAL.">{itens.map((l,i)=><div key={i} className="grid min-w-0 gap-3 rounded-xl border p-4 sm:grid-cols-2 lg:grid-cols-3"><BarraLinha titulo={`ITEM ${i+1}`} excluir={()=>excluir(setItens,itens,i)}/><label className="min-w-0 text-sm font-bold sm:col-span-2 lg:col-span-3">ITEM<select value={l.item} onChange={e=>trocarPreset(itens,setItens,i,itemPreparado(ITENS_APLICACAO.find(x=>x.item===e.target.value)||ITENS_APLICACAO[0]))} className={campo}>{ITENS_APLICACAO.map(x=><option key={x.item}>{x.item}</option>)}</select></label><div className="sm:col-span-2 lg:col-span-3"><CampoArea titulo="DESCRIÇÃO" valor={l.descricao} mudar={v=>alterarItem(i,"descricao",v)}/></div>{["quantidade","unidade","valorUnitario","valorTotal"].map(k=><label key={k} className="min-w-0 text-sm font-bold">{k.toUpperCase()}<input value={l[k]} readOnly={k==="valorTotal"} onChange={e=>alterarItem(i,k,e.target.value)} className={`${campo} ${k==="valorTotal"?"bg-slate-100 font-black text-emerald-900":""}`}/></label>)}</div>)}<BotaoAdicionar texto="INCLUIR ITEM" clicar={()=>setItens([...itens,itemPreparado(ITENS_APLICACAO[0])])}/><p className="text-right text-xl font-black text-emerald-900">TOTAL DO ORÇAMENTO: {itens.reduce((s,x)=>s+numero(x.valorTotal),0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}</p></Bloco>
  <div className="sticky bottom-3 rounded-xl border bg-white/95 p-4 shadow-lg"><button type="button" onClick={gerar} disabled={gerando||!culturas.length} className="h-12 w-full rounded-xl bg-emerald-800 font-black text-white disabled:opacity-50">{gerando?"GERANDO DOCUMENTO...":"GERAR PLANO DE TRABALHO EM WORD"}</button>{!culturas.length&&<p className="mt-2 text-center text-sm font-bold text-amber-700">SELECIONE AO MENOS UMA CULTURA.</p>}{msg&&<p className="mt-2 text-center text-sm font-bold">{msg}</p>}</div>
 </div>;
}

function Bloco({titulo,subtitulo,children}:{titulo:string;subtitulo:string;children:React.ReactNode}){return <section className="space-y-4"><div><h2 className="text-xl font-black">{titulo}</h2><p className="text-sm text-slate-600">{subtitulo}</p></div>{children}</section>}
function CampoArea({titulo,valor,mudar}:{titulo:string;valor:string;mudar:(v:string)=>void}){return <label className="text-sm font-bold">{titulo}<textarea value={valor} onChange={e=>mudar(e.target.value)} className={area}/></label>}
function BarraLinha({titulo,excluir}:{titulo:string;excluir:()=>void}){return <div className="col-span-full flex items-center justify-between gap-3 border-b pb-2"><p className="font-black text-emerald-900">{titulo}</p><button type="button" onClick={excluir} className="inline-flex h-9 items-center gap-2 rounded-lg border border-red-300 px-3 text-xs font-black text-red-700"><Trash2 className="h-4 w-4"/>EXCLUIR</button></div>}
function BotaoAdicionar({texto,clicar}:{texto:string;clicar:()=>void}){return <button type="button" onClick={clicar} className="inline-flex h-11 items-center gap-2 rounded-lg border border-emerald-700 bg-emerald-50 px-4 text-sm font-black text-emerald-900"><Plus className="h-4 w-4"/>{texto}</button>}
