"use client";
import {useEffect,useState} from "react";
import {Plus,Trash2} from "lucide-react";
import {CARGOS_EQUIPE,CULTURAS_PLANO,ETAPAS_PLANO,ITENS_APLICACAO,OBJETIVOS_MONITORAMENTO} from "@/lib/plano-associacao";

type Linha=Record<string,string>;
const campo="mt-1 h-11 w-full rounded-lg border bg-white px-3 text-sm";
const area="mt-1 min-h-24 w-full rounded-lg border bg-white p-3 text-sm";
const copia=<T extends readonly object[]>(itens:T)=>itens.map(item=>({...item})) as Linha[];
function numero(valor:string){return Number(valor.replace(/\./g,"").replace(",","."))||0;}
function quantidadeFormatada(valor:string){const digitos=valor.replace(/\D/g,"");return digitos?Number(digitos).toLocaleString("pt-BR"):"";}
function valorFormatado(valor:number){return valor.toLocaleString("pt-BR",{minimumFractionDigits:2,maximumFractionDigits:2});}
function dividirValor(total:number,parcelas:number){const centavos=Math.round(total*100),base=Math.floor(centavos/parcelas),restante=centavos-base*parcelas;return Array.from({length:parcelas},(_,indice)=>valorFormatado((base+(indice<restante?1:0))/100));}
function itemPreparado(item:object){const linha={...item} as Linha;linha.quantidade=quantidadeFormatada(linha.quantidade||"");linha.valorTotal=valorFormatado(numero(linha.quantidade)*numero(linha.valorUnitario));return linha;}
function nomeItem(valor:string){return valor.replace(/^\s*\d+(?:[.,]\d+)?\s*[-–—:]\s*/,"").trim();}
function chave(valor:string){return valor.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLocaleUpperCase("pt-BR").replace(/[^A-Z0-9]/g,"");}
const ITEM_POR_CARGO:Record<string,string>={TECNICODECAMPO:"TECNICOSDECAMPO",SERVICODEAPOIOADMINISTRATIVO:"SERVICODEAPOIOADMINISTRATIVO",CONSULTORDEPROJETO:"CONSULTORDEPROJETO",SUBCOORDENADOR:"SUBCOORDENADOR",CONSULTORDEARTICULACAOEIMPACTOSOCIAL:"CONSULTORDEARTICULACAOEIMPACTOSOCIAL",TECNICODECOMUNICACAO:"TECNICODECOMUNICACAO"};
function presetDoCargo(cargo:string){const procurado=ITEM_POR_CARGO[chave(cargo)]||chave(cargo);return ITENS_APLICACAO.find(item=>chave(nomeItem(item.item)).includes(procurado));}
function recursosDaEquipe(equipe:Linha[]){return equipe.flatMap(linha=>{const preset=presetDoCargo(linha.cargo||"");if(!preset)return[];const cargoPadrao=CARGOS_EQUIPE.find(item=>item.cargo===linha.cargo);const profissionais=Math.max(0,numero(linha.numero||"0"));const profissionaisPadrao=Math.max(1,numero(cargoPadrao?.numero||"1"));const quantidade=numero(preset.quantidade)*(profissionais/profissionaisPadrao);return[itemPreparado({...preset,item:nomeItem(preset.item),quantidade:String(quantidade),_cargoEquipe:linha.cargo})];});}

export default function PlanoAssociacaoForm({associacao,itensPersonalizados}:{associacao:{id:number;nome:string;razaoSocial:string;municipiosJson:string};itensPersonalizados:Linha[]}){
 let municipios:string[]=[];try{municipios=JSON.parse(associacao.municipiosJson||"[]");}catch{}
 const[culturas,setCulturas]=useState<string[]>([]);const[inicio,setInicio]=useState("MARÇO DE 2026");const[termino,setTermino]=useState("MARÇO DE 2027");
 const itensIniciais=[...ITENS_APLICACAO.map(item=>itemPreparado({...item,item:nomeItem(item.item)})),...itensPersonalizados.map(itemPreparado)].filter((item,indice,lista)=>lista.findIndex(outro=>outro.item===item.item)===indice);const equipeInicial=copia(CARGOS_EQUIPE.slice(0,4));const[etapas,setEtapas]=useState<Linha[]>(copia(ETAPAS_PLANO));const[objetivos,setObjetivos]=useState<Linha[]>(copia(OBJETIVOS_MONITORAMENTO));const[equipe,setEquipe]=useState<Linha[]>(equipeInicial);const[opcoesItens,setOpcoesItens]=useState<Linha[]>(itensIniciais);const[itens,setItens]=useState<Linha[]>(()=>recursosDaEquipe(equipeInicial));
 const[repasses,setRepasses]=useState([{mes:"MARÇO/2026",valor:"0,00"}]);const[gerando,setGerando]=useState(false);const[msg,setMsg]=useState("");const[passo,setPasso]=useState(1);const totalOrcamento=itens.reduce((s,x)=>s+numero(x.valorTotal),0);const totalRepasses=repasses.reduce((s,x)=>s+numero(x.valor),0);const saldoRepasses=totalOrcamento-totalRepasses;
 useEffect(()=>{if(repasses.length!==1)return;const valor=valorFormatado(totalOrcamento);if(repasses[0].valor!==valor)setRepasses([{...repasses[0],valor}])},[totalOrcamento,repasses]);
 useEffect(()=>{setItens(atuais=>{const automaticos=recursosDaEquipe(equipe);const manuais=atuais.filter(item=>!item._cargoEquipe);return[...automaticos.map(novo=>{const existente=atuais.find(item=>item._cargoEquipe===novo._cargoEquipe);return existente?{...existente,item:novo.item,quantidade:novo.quantidade,valorTotal:valorFormatado(numero(novo.quantidade)*numero(existente.valorUnitario||novo.valorUnitario))}:novo}),...manuais.filter(item=>!automaticos.some(auto=>auto.item===item.item))]})},[equipe]);
 function trocarPreset(lista:Linha[],setLista:(v:Linha[])=>void,indice:number,preset:object){const nova=[...lista];nova[indice]={...preset} as Linha;setLista(nova)}
 function alterar(lista:Linha[],setLista:(v:Linha[])=>void,indice:number,chave:string,valor:string){const nova=[...lista];nova[indice]={...nova[indice],[chave]:valor};setLista(nova)}
 function adicionar(setLista:(v:Linha[])=>void,lista:Linha[],preset:object){setLista([...lista,{...preset} as Linha])}
 function excluir(setLista:(v:Linha[])=>void,lista:Linha[],indice:number){setLista(lista.filter((_,i)=>i!==indice))}
 function adicionarRepasse(){const novos=[...repasses,{mes:"",valor:""}],valores=dividirValor(totalOrcamento,novos.length);setRepasses(novos.map((repasse,indice)=>({...repasse,valor:valores[indice]})))}
 function alterarItem(indice:number,chave:string,valor:string){const nova=[...itens];const atual={...nova[indice],[chave]:chave==="quantidade"?quantidadeFormatada(valor):valor};if(chave==="quantidade"||chave==="valorUnitario")atual.valorTotal=valorFormatado(numero(atual.quantidade)*numero(atual.valorUnitario));nova[indice]=atual;setItens(nova)}
 async function cadastrarNovoItem(indice:number){const informado=window.prompt("INFORME O NOME DO NOVO ITEM:","");const nome=String(informado||"").trim().toLocaleUpperCase("pt-BR");if(!nome)return;const existente=opcoesItens.find(item=>item.item.toLocaleUpperCase("pt-BR")===nome);const novo=existente||{item:nome,descricao:"",quantidade:"",unidade:"",valorUnitario:"",valorTotal:"0,00"};if(!existente){const resposta=await fetch("/api/admin/associacoes/plano-trabalho/itens",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(novo)});if(!resposta.ok){window.alert("NÃO FOI POSSÍVEL SALVAR O NOVO ITEM.");return}setOpcoesItens([...opcoesItens,novo])}const atualizados=[...itens];atualizados[indice]={...novo};setItens(atualizados)}
 async function gerar(){setGerando(true);setMsg("");try{if(Math.abs(totalRepasses-totalOrcamento)>0.01)throw new Error(`A SOMA DOS REPASSES DEVE SER IGUAL AO TOTAL DO ORÇAMENTO (${valorFormatado(totalOrcamento)}).`);const personalizados=itens.filter(item=>!ITENS_APLICACAO.some(padrao=>nomeItem(padrao.item)===item.item));if(personalizados.length)await fetch("/api/admin/associacoes/plano-trabalho/itens",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({itens:personalizados})});const resposta=await fetch("/api/admin/associacoes/plano-trabalho",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({associacaoId:associacao.id,inicio,termino,culturas,etapas,objetivos,equipe,itens,repasses})});if(!resposta.ok){const erro=await resposta.json().catch(()=>({}));throw new Error(erro.message||"NÃO FOI POSSÍVEL GERAR O PLANO.")}const blob=await resposta.blob();const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`PLANO_DE_TRABALHO_${associacao.nome.replace(/\W+/g,"_")}.docx`;a.click();URL.revokeObjectURL(url);setMsg("PLANO DE TRABALHO GERADO COM SUCESSO.");}catch(e){setMsg(e instanceof Error?e.message:"NÃO FOI POSSÍVEL GERAR.")}finally{setGerando(false)}}
 return <div className="mt-6 space-y-7">
  <section className="grid gap-3 rounded-xl bg-emerald-950 p-4 text-white sm:grid-cols-4"><div className="sm:col-span-2"><p className="text-xs font-bold text-emerald-200">ASSOCIAÇÃO</p><p className="mt-1 font-black">{associacao.nome}</p><p className="text-xs text-emerald-100">{associacao.razaoSocial}</p></div><div><p className="text-xs font-bold text-emerald-200">MUNICÍPIOS</p><p className="mt-1 text-lg font-black">{municipios.length}</p></div><div><p className="text-xs font-bold text-emerald-200">ORÇAMENTO ATUAL</p><p className="mt-1 text-lg font-black">{totalOrcamento.toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}</p></div></section>
  <nav className="grid gap-2 sm:grid-cols-5" aria-label="ETAPAS DO GERADOR">{["IDENTIFICAÇÃO","METODOLOGIA","MONITORAMENTO","EQUIPE","RECURSOS"].map((nome,i)=><button key={nome} type="button" onClick={()=>setPasso(i+1)} className={`min-h-12 rounded-xl border px-3 text-xs font-black ${passo===i+1?"border-emerald-800 bg-emerald-800 text-white":"bg-white text-slate-700"}`}><span className="mr-1">{i+1}.</span>{nome}</button>)}</nav>
  {passo===1&&<section className="grid gap-4 rounded-xl border bg-slate-50 p-5 sm:grid-cols-2"><div className="sm:col-span-2"><p className="font-black text-emerald-900">IDENTIFICAÇÃO E PERÍODO</p><p className="text-sm text-slate-600">MUNICÍPIOS ATENDIDOS: {municipios.join(" · ")||"NÃO CADASTRADOS"}</p></div><label className="text-sm font-bold">INÍCIO DO PERÍODO<input value={inicio} onChange={e=>setInicio(e.target.value)} className={campo}/></label><label className="text-sm font-bold">TÉRMINO DO PERÍODO<input value={termino} onChange={e=>setTermino(e.target.value)} className={campo}/></label><fieldset className="sm:col-span-2"><legend className="text-sm font-bold">CULTURAS DA ASSOCIAÇÃO</legend><div className="mt-2 grid gap-2 sm:grid-cols-3 lg:grid-cols-4">{CULTURAS_PLANO.map(c=><label key={c} className="flex items-center gap-2 rounded-lg border bg-white p-2 text-sm"><input type="checkbox" checked={culturas.includes(c)} onChange={()=>setCulturas(x=>x.includes(c)?x.filter(v=>v!==c):[...x,c])}/>{c}</label>)}</div></fieldset></section>}
  {passo===2&&<Bloco titulo="DETALHAMENTO METODOLÓGICO" subtitulo="AO ESCOLHER A ETAPA, OS DEMAIS CAMPOS SÃO PREENCHIDOS AUTOMATICAMENTE.">{etapas.map((l,i)=><div key={i} className="grid min-w-0 gap-3 rounded-xl border p-4 lg:grid-cols-2"><BarraLinha titulo={`ETAPA ${i+1}`} excluir={()=>excluir(setEtapas,etapas,i)}/><label className="min-w-0 text-sm font-bold">ETAPA<select value={l.nome} onChange={e=>trocarPreset(etapas,setEtapas,i,ETAPAS_PLANO.find(x=>x.nome===e.target.value)||ETAPAS_PLANO[0])} className={campo}>{ETAPAS_PLANO.map(x=><option key={x.nome}>{x.nome}</option>)}</select></label><CampoArea titulo="OBJETIVO ESPECÍFICO" valor={l.objetivo} mudar={v=>alterar(etapas,setEtapas,i,"objetivo",v)}/><CampoArea titulo="AÇÕES" valor={l.acoes} mudar={v=>alterar(etapas,setEtapas,i,"acoes",v)}/><CampoArea titulo="METAS" valor={l.metas} mudar={v=>alterar(etapas,setEtapas,i,"metas",v)}/><CampoArea titulo="RESULTADOS ESPERADOS" valor={l.resultados} mudar={v=>alterar(etapas,setEtapas,i,"resultados",v)}/></div>)}<BotaoAdicionar texto="INCLUIR ETAPA" clicar={()=>adicionar(setEtapas,etapas,ETAPAS_PLANO[0])}/></Bloco>}
  {passo===3&&<Bloco titulo="MATRIZ DE MONITORAMENTO E AVALIAÇÃO" subtitulo="AO ESCOLHER O OBJETIVO, OS INDICADORES E DEMAIS CAMPOS SÃO PREENCHIDOS.">{objetivos.map((l,i)=><div key={i} className="grid min-w-0 gap-3 rounded-xl border p-4 lg:grid-cols-2"><BarraLinha titulo={`OBJETIVO ${i+1}`} excluir={()=>excluir(setObjetivos,objetivos,i)}/><label className="min-w-0 text-sm font-bold lg:col-span-2">OBJETIVO ESPECÍFICO<select value={l.objetivo} onChange={e=>trocarPreset(objetivos,setObjetivos,i,OBJETIVOS_MONITORAMENTO.find(x=>x.objetivo===e.target.value)||OBJETIVOS_MONITORAMENTO[0])} className={campo}>{OBJETIVOS_MONITORAMENTO.map(x=><option key={x.objetivo}>{x.objetivo}</option>)}</select></label>{["quantitativos","qualitativos","fonte","coleta","responsavel","periodicidade"].map(k=><CampoArea key={k} titulo={k.toUpperCase()} valor={l[k]} mudar={v=>alterar(objetivos,setObjetivos,i,k,v)}/>)}</div>)}<BotaoAdicionar texto="INCLUIR OBJETIVO" clicar={()=>adicionar(setObjetivos,objetivos,OBJETIVOS_MONITORAMENTO[0])}/></Bloco>}
  {passo===4&&<Bloco titulo="EQUIPE TÉCNICA" subtitulo="O CARGO PREENCHE AS ATRIBUIÇÕES. NÚMERO DE PROFISSIONAIS E ESCOLARIDADE PERMANECEM EDITÁVEIS.">{equipe.map((l,i)=><div key={i} className="grid min-w-0 gap-3 rounded-xl border p-4 sm:grid-cols-2 lg:grid-cols-4"><BarraLinha titulo={`PROFISSIONAL / CARGO ${i+1}`} excluir={()=>excluir(setEquipe,equipe,i)}/><label className="min-w-0 text-sm font-bold sm:col-span-2">CARGO<select value={l.cargo} onChange={e=>trocarPreset(equipe,setEquipe,i,CARGOS_EQUIPE.find(x=>x.cargo===e.target.value)||CARGOS_EQUIPE[0])} className={campo}>{CARGOS_EQUIPE.map(x=><option key={x.cargo}>{x.cargo}</option>)}</select></label>{["numero","escolaridade","periodo","natureza"].map(k=><label key={k} className="min-w-0 text-sm font-bold">{k.toUpperCase()}<input value={l[k]} onChange={e=>alterar(equipe,setEquipe,i,k,e.target.value)} className={campo}/></label>)}<div className="sm:col-span-2 lg:col-span-4"><CampoArea titulo="ATRIBUIÇÕES" valor={l.atribuicoes} mudar={v=>alterar(equipe,setEquipe,i,"atribuicoes",v)}/></div></div>)}<BotaoAdicionar texto="INCLUIR PROFISSIONAL / CARGO" clicar={()=>adicionar(setEquipe,equipe,CARGOS_EQUIPE[0])}/></Bloco>}
  {passo===5&&<><Bloco titulo="CRONOGRAMA DE DESEMBOLSO DO REPASSE" subtitulo="AO INCLUIR UM REPASSE, O TOTAL DO ORÇAMENTO É DIVIDIDO AUTOMATICAMENTE EM PARTES IGUAIS. OS VALORES PERMANECEM EDITÁVEIS."><div className="grid gap-3 sm:grid-cols-2">{repasses.map((r,i)=><div key={i} className="grid min-w-0 grid-cols-2 gap-3 rounded-xl border p-4"><BarraLinha titulo={`REPASSE ${i+1}`} excluir={()=>setRepasses(repasses.filter((_,x)=>x!==i))}/><label className="min-w-0 text-sm font-bold">MÊS<input value={r.mes} onChange={e=>{const n=[...repasses];n[i]={...r,mes:e.target.value};setRepasses(n)}} className={campo}/></label><label className="min-w-0 text-sm font-bold">VALOR (R$)<input value={r.valor} onChange={e=>{const n=[...repasses];n[i]={...r,valor:e.target.value};setRepasses(n)}} className={campo}/></label></div>)}</div><BotaoAdicionar texto="INCLUIR REPASSE E DIVIDIR VALORES" clicar={adicionarRepasse}/><div className={`rounded-xl border p-4 text-right ${Math.abs(saldoRepasses)<0.01?"border-emerald-200 bg-emerald-50 text-emerald-900":"border-amber-300 bg-amber-50 text-amber-900"}`}><p className="text-sm font-bold">TOTAL DO ORÇAMENTO: {valorFormatado(totalOrcamento)}</p><p className="text-sm font-bold">TOTAL DOS REPASSES: {valorFormatado(totalRepasses)}</p><p className="mt-1 text-lg font-black">{Math.abs(saldoRepasses)<0.01?"VALORES CONFERIDOS":`${saldoRepasses>0?"FALTA DISTRIBUIR":"VALOR EXCEDENTE"}: ${valorFormatado(Math.abs(saldoRepasses))}`}</p></div></Bloco>
  <Bloco titulo="PLANO DE APLICAÇÃO DE RECURSOS" subtitulo="OS RECURSOS DA EQUIPE SÃO INCLUÍDOS AUTOMATICAMENTE CONFORME O CARGO E O NÚMERO DE PROFISSIONAIS. OUTROS ITENS PODEM SER INCLUÍDOS PELO BOTÃO ABAIXO."><BotaoAdicionar texto="INCLUIR ITEM NO PLANO" clicar={()=>setItens([...itens,{...opcoesItens[0]}])} icone={false}/>{!itens.length&&<p className="rounded-xl border border-dashed border-emerald-300 bg-emerald-50 p-5 text-center text-sm font-bold text-emerald-900">NENHUM ITEM INCLUÍDO NO PLANO.</p>}{itens.map((l,i)=><div key={i} className="grid min-w-0 gap-3 rounded-xl border p-4 sm:grid-cols-2 lg:grid-cols-3"><BarraLinha titulo={l._cargoEquipe?`RECURSO DA EQUIPE · ${l._cargoEquipe}`:"ITEM CADASTRADO"} excluir={()=>excluir(setItens,itens,i)}/><div className="min-w-0 sm:col-span-2 lg:col-span-3"><p className="text-sm font-bold">ITEM</p><div className="mt-1 flex gap-2"><select value={l.item} onChange={e=>trocarPreset(itens,setItens,i,{...(opcoesItens.find(x=>x.item===e.target.value)||opcoesItens[0])})} className="h-11 min-w-0 flex-1 rounded-lg border bg-white px-3 text-sm">{opcoesItens.map((x,indice)=><option key={`${x.item}-${indice}`} value={x.item}>{x.item}</option>)}</select><button type="button" onClick={()=>cadastrarNovoItem(i)} title="CADASTRAR NOVO ITEM" aria-label="CADASTRAR NOVO ITEM" className="inline-flex h-11 w-11 shrink-0 items-center justify-center rounded-lg bg-emerald-800 text-white"><Plus className="h-5 w-5"/></button></div></div><div className="sm:col-span-2 lg:col-span-3"><CampoArea titulo="DESCRIÇÃO" valor={l.descricao} mudar={v=>alterarItem(i,"descricao",v)}/></div>{["quantidade","unidade","valorUnitario","valorTotal"].map(k=><label key={k} className="min-w-0 text-sm font-bold">{k.toUpperCase()}<input value={l[k]} readOnly={k==="valorTotal"} onChange={e=>alterarItem(i,k,e.target.value)} className={`${campo} ${k==="valorTotal"?"bg-slate-100 font-black text-emerald-900":""}`}/></label>)}</div>)}<p className="text-right text-xl font-black text-emerald-900">TOTAL DO ORÇAMENTO: {itens.reduce((s,x)=>s+numero(x.valorTotal),0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}</p></Bloco></>}
  <div className="flex flex-wrap items-center justify-between gap-3 rounded-xl border bg-slate-50 p-4"><button type="button" disabled={passo===1} onClick={()=>setPasso(p=>Math.max(1,p-1))} className="h-11 rounded-lg border px-5 font-black disabled:opacity-40">ANTERIOR</button><p className="text-sm font-bold text-slate-600">ETAPA {passo} DE 5</p><button type="button" disabled={passo===5} onClick={()=>setPasso(p=>Math.min(5,p+1))} className="h-11 rounded-lg bg-emerald-800 px-5 font-black text-white disabled:opacity-40">PRÓXIMA</button></div>
  <div className="sticky bottom-3 rounded-xl border bg-white/95 p-4 shadow-lg"><button type="button" onClick={gerar} disabled={gerando||!culturas.length} className="h-12 w-full rounded-xl bg-emerald-800 font-black text-white disabled:opacity-50">{gerando?"GERANDO DOCUMENTO...":"GERAR PLANO DE TRABALHO EM WORD"}</button>{!culturas.length&&<p className="mt-2 text-center text-sm font-bold text-amber-700">SELECIONE AO MENOS UMA CULTURA.</p>}{msg&&<p className="mt-2 text-center text-sm font-bold">{msg}</p>}</div>
 </div>;
}

function Bloco({titulo,subtitulo,children}:{titulo:string;subtitulo:string;children:React.ReactNode}){return <section className="space-y-4"><div><h2 className="text-xl font-black">{titulo}</h2><p className="text-sm text-slate-600">{subtitulo}</p></div>{children}</section>}
function CampoArea({titulo,valor,mudar}:{titulo:string;valor:string;mudar:(v:string)=>void}){return <label className="text-sm font-bold">{titulo}<textarea value={valor} onChange={e=>mudar(e.target.value)} className={area}/></label>}
function BarraLinha({titulo,excluir}:{titulo:string;excluir:()=>void}){return <div className="col-span-full flex items-center justify-between gap-3 border-b pb-2"><p className="font-black text-emerald-900">{titulo}</p><button type="button" onClick={excluir} className="inline-flex h-9 items-center gap-2 rounded-lg border border-red-300 px-3 text-xs font-black text-red-700"><Trash2 className="h-4 w-4"/>EXCLUIR</button></div>}
function BotaoAdicionar({texto,clicar,icone=true}:{texto:string;clicar:()=>void;icone?:boolean}){return <button type="button" onClick={clicar} className="inline-flex h-11 items-center gap-2 rounded-lg border border-emerald-700 bg-emerald-50 px-4 text-sm font-black text-emerald-900">{icone&&<Plus className="h-4 w-4"/>}{texto}</button>}
