"use client";
import {useState} from "react";
import {CARGOS_EQUIPE,CULTURAS_PLANO,ETAPAS_PLANO,ITENS_APLICACAO,OBJETIVOS_MONITORAMENTO} from "@/lib/plano-associacao";

type Linha=Record<string,string>;
const campo="mt-1 h-11 w-full rounded-lg border bg-white px-3 text-sm";
const area="mt-1 min-h-24 w-full rounded-lg border bg-white p-3 text-sm";
const copia=<T extends readonly object[]>(itens:T)=>itens.map(item=>({...item})) as Linha[];
function numero(valor:string){return Number(valor.replace(/\./g,"").replace(",","."))||0;}

export default function PlanoAssociacaoForm({associacao}:{associacao:{id:number;nome:string;razaoSocial:string;municipiosJson:string}}){
 let municipios:string[]=[];try{municipios=JSON.parse(associacao.municipiosJson||"[]");}catch{}
 const[culturas,setCulturas]=useState<string[]>([]);const[inicio,setInicio]=useState("MARÇO DE 2026");const[termino,setTermino]=useState("MARÇO DE 2027");
 const[etapas,setEtapas]=useState<Linha[]>(copia(ETAPAS_PLANO));const[objetivos,setObjetivos]=useState<Linha[]>(copia(OBJETIVOS_MONITORAMENTO));const[equipe,setEquipe]=useState<Linha[]>(copia(CARGOS_EQUIPE.slice(0,4)));const[itens,setItens]=useState<Linha[]>(copia(ITENS_APLICACAO));
 const[repasses,setRepasses]=useState([{mes:"MARÇO/2026",valor:"365386,00"},{mes:"ABRIL/2026",valor:"365386,00"}]);const[gerando,setGerando]=useState(false);const[msg,setMsg]=useState("");
 function trocarPreset(lista:Linha[],setLista:(v:Linha[])=>void,indice:number,preset:object){const nova=[...lista];nova[indice]={...preset} as Linha;setLista(nova)}
 function alterar(lista:Linha[],setLista:(v:Linha[])=>void,indice:number,chave:string,valor:string){const nova=[...lista];nova[indice]={...nova[indice],[chave]:valor};setLista(nova)}
 async function gerar(){setGerando(true);setMsg("");try{const resposta=await fetch("/api/admin/associacoes/plano-trabalho",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({associacaoId:associacao.id,inicio,termino,culturas,etapas,objetivos,equipe,itens,repasses})});if(!resposta.ok){const erro=await resposta.json().catch(()=>({}));throw new Error(erro.message||"NÃO FOI POSSÍVEL GERAR O PLANO.")}const blob=await resposta.blob();const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`PLANO_DE_TRABALHO_${associacao.nome.replace(/\W+/g,"_")}.docx`;a.click();URL.revokeObjectURL(url);setMsg("PLANO DE TRABALHO GERADO COM SUCESSO.");}catch(e){setMsg(e instanceof Error?e.message:"NÃO FOI POSSÍVEL GERAR.")}finally{setGerando(false)}}
 return <div className="mt-6 space-y-7">
  <section className="grid gap-4 rounded-xl border bg-slate-50 p-5 sm:grid-cols-2"><div className="sm:col-span-2"><p className="font-black text-emerald-900">{associacao.razaoSocial}</p><p className="text-sm text-slate-600">MUNICÍPIOS ATENDIDOS: {municipios.join(" · ")||"NÃO CADASTRADOS"}</p></div><label className="text-sm font-bold">INÍCIO DO PERÍODO<input value={inicio} onChange={e=>setInicio(e.target.value)} className={campo}/></label><label className="text-sm font-bold">TÉRMINO DO PERÍODO<input value={termino} onChange={e=>setTermino(e.target.value)} className={campo}/></label><fieldset className="sm:col-span-2"><legend className="text-sm font-bold">CULTURAS DA ASSOCIAÇÃO</legend><div className="mt-2 grid gap-2 sm:grid-cols-3 lg:grid-cols-4">{CULTURAS_PLANO.map(c=><label key={c} className="flex items-center gap-2 rounded-lg border bg-white p-2 text-sm"><input type="checkbox" checked={culturas.includes(c)} onChange={()=>setCulturas(x=>x.includes(c)?x.filter(v=>v!==c):[...x,c])}/>{c}</label>)}</div></fieldset></section>
  <Bloco titulo="DETALHAMENTO METODOLÓGICO" subtitulo="AO ESCOLHER A ETAPA, OS DEMAIS CAMPOS SÃO PREENCHIDOS AUTOMATICAMENTE.">{etapas.map((l,i)=><div key={i} className="grid gap-3 rounded-xl border p-4 lg:grid-cols-2"><label className="text-sm font-bold">ETAPA<select value={l.nome} onChange={e=>trocarPreset(etapas,setEtapas,i,ETAPAS_PLANO.find(x=>x.nome===e.target.value)||ETAPAS_PLANO[0])} className={campo}>{ETAPAS_PLANO.map(x=><option key={x.nome}>{x.nome}</option>)}</select></label><CampoArea titulo="OBJETIVO ESPECÍFICO" valor={l.objetivo} mudar={v=>alterar(etapas,setEtapas,i,"objetivo",v)}/><CampoArea titulo="AÇÕES" valor={l.acoes} mudar={v=>alterar(etapas,setEtapas,i,"acoes",v)}/><CampoArea titulo="METAS" valor={l.metas} mudar={v=>alterar(etapas,setEtapas,i,"metas",v)}/><CampoArea titulo="RESULTADOS ESPERADOS" valor={l.resultados} mudar={v=>alterar(etapas,setEtapas,i,"resultados",v)}/></div>)}</Bloco>
  <Bloco titulo="MATRIZ DE MONITORAMENTO E AVALIAÇÃO" subtitulo="AO ESCOLHER O OBJETIVO, OS INDICADORES E DEMAIS CAMPOS SÃO PREENCHIDOS.">{objetivos.map((l,i)=><div key={i} className="grid gap-3 rounded-xl border p-4 lg:grid-cols-2"><label className="text-sm font-bold lg:col-span-2">OBJETIVO ESPECÍFICO<select value={l.objetivo} onChange={e=>trocarPreset(objetivos,setObjetivos,i,OBJETIVOS_MONITORAMENTO.find(x=>x.objetivo===e.target.value)||OBJETIVOS_MONITORAMENTO[0])} className={campo}>{OBJETIVOS_MONITORAMENTO.map(x=><option key={x.objetivo}>{x.objetivo}</option>)}</select></label>{["quantitativos","qualitativos","fonte","coleta","responsavel","periodicidade"].map(k=><CampoArea key={k} titulo={k.toUpperCase()} valor={l[k]} mudar={v=>alterar(objetivos,setObjetivos,i,k,v)}/>)}</div>)}</Bloco>
  <Bloco titulo="EQUIPE TÉCNICA" subtitulo="O CARGO PREENCHE AS ATRIBUIÇÕES. NÚMERO DE PROFISSIONAIS E ESCOLARIDADE PERMANECEM EDITÁVEIS.">{equipe.map((l,i)=><div key={i} className="grid gap-3 rounded-xl border p-4 sm:grid-cols-2 lg:grid-cols-4"><label className="text-sm font-bold sm:col-span-2">CARGO<select value={l.cargo} onChange={e=>trocarPreset(equipe,setEquipe,i,CARGOS_EQUIPE.find(x=>x.cargo===e.target.value)||CARGOS_EQUIPE[0])} className={campo}>{CARGOS_EQUIPE.map(x=><option key={x.cargo}>{x.cargo}</option>)}</select></label>{["numero","escolaridade","periodo","natureza"].map(k=><label key={k} className="text-sm font-bold">{k.toUpperCase()}<input value={l[k]} onChange={e=>alterar(equipe,setEquipe,i,k,e.target.value)} className={campo}/></label>)}<div className="sm:col-span-2 lg:col-span-4"><CampoArea titulo="ATRIBUIÇÕES" valor={l.atribuicoes} mudar={v=>alterar(equipe,setEquipe,i,"atribuicoes",v)}/></div></div>)}</Bloco>
  <Bloco titulo="CRONOGRAMA DE DESEMBOLSO DO REPASSE" subtitulo="MESES E VALORES EDITÁVEIS."><div className="grid gap-3 sm:grid-cols-2">{repasses.map((r,i)=><div key={i} className="grid grid-cols-2 gap-3 rounded-xl border p-4"><label className="text-sm font-bold">MÊS<input value={r.mes} onChange={e=>{const n=[...repasses];n[i]={...r,mes:e.target.value};setRepasses(n)}} className={campo}/></label><label className="text-sm font-bold">VALOR (R$)<input value={r.valor} onChange={e=>{const n=[...repasses];n[i]={...r,valor:e.target.value};setRepasses(n)}} className={campo}/></label></div>)}</div></Bloco>
  <Bloco titulo="PLANO DE APLICAÇÃO DE RECURSOS" subtitulo="AO ESCOLHER O ITEM, DESCRIÇÃO E VALORES SÃO PREENCHIDOS. O ORÇAMENTO SERÁ CALCULADO A PARTIR DESTA SEÇÃO.">{itens.map((l,i)=><div key={i} className="grid gap-3 rounded-xl border p-4 sm:grid-cols-2 lg:grid-cols-3"><label className="text-sm font-bold sm:col-span-2 lg:col-span-3">ITEM<select value={l.item} onChange={e=>trocarPreset(itens,setItens,i,ITENS_APLICACAO.find(x=>x.item===e.target.value)||ITENS_APLICACAO[0])} className={campo}>{ITENS_APLICACAO.map(x=><option key={x.item}>{x.item}</option>)}</select></label><div className="sm:col-span-2 lg:col-span-3"><CampoArea titulo="DESCRIÇÃO" valor={l.descricao} mudar={v=>alterar(itens,setItens,i,"descricao",v)}/></div>{["quantidade","unidade","valorUnitario","valorTotal"].map(k=><label key={k} className="text-sm font-bold">{k.toUpperCase()}<input value={l[k]} onChange={e=>alterar(itens,setItens,i,k,e.target.value)} className={campo}/></label>)}</div>)}<p className="text-right text-xl font-black text-emerald-900">TOTAL DO ORÇAMENTO: {itens.reduce((s,x)=>s+numero(x.valorTotal),0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}</p></Bloco>
  <div className="sticky bottom-3 rounded-xl border bg-white/95 p-4 shadow-lg"><button type="button" onClick={gerar} disabled={gerando||!culturas.length} className="h-12 w-full rounded-xl bg-emerald-800 font-black text-white disabled:opacity-50">{gerando?"GERANDO DOCUMENTO...":"GERAR PLANO DE TRABALHO EM WORD"}</button>{!culturas.length&&<p className="mt-2 text-center text-sm font-bold text-amber-700">SELECIONE AO MENOS UMA CULTURA.</p>}{msg&&<p className="mt-2 text-center text-sm font-bold">{msg}</p>}</div>
 </div>;
}

function Bloco({titulo,subtitulo,children}:{titulo:string;subtitulo:string;children:React.ReactNode}){return <section className="space-y-4"><div><h2 className="text-xl font-black">{titulo}</h2><p className="text-sm text-slate-600">{subtitulo}</p></div>{children}</section>}
function CampoArea({titulo,valor,mudar}:{titulo:string;valor:string;mudar:(v:string)=>void}){return <label className="text-sm font-bold">{titulo}<textarea value={valor} onChange={e=>mudar(e.target.value)} className={area}/></label>}
