import {eq} from "drizzle-orm";
import {strFromU8,strToU8,unzipSync,zipSync} from "fflate";
import {getAdminUser} from "@/lib/admin";
import {getDb} from "@/db";
import {associacoes} from "@/db/schema";

export const runtime="edge";
type Linha=Record<string,string>;
function xml(valor:unknown){return String(valor??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&apos;").replace(/\r?\n/g,"</w:t><w:br/><w:t xml:space=\"preserve\">");}
function moeda(valor:string){const n=Number(String(valor||"").replace(/\./g,"").replace(",","."))||0;return n.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});}
function colocar(documento:string,chave:string,valor:unknown){return documento.split(`{{${chave}}}`).join(xml(valor));}

export async function POST(request:Request){
 if(!await getAdminUser())return Response.json({message:"ACESSO RESTRITO."},{status:403});
 try{
  const dados=await request.json() as {associacaoId:number;inicio:string;termino:string;culturas:string[];etapas:Linha[];objetivos:Linha[];equipe:Linha[];itens:Linha[];repasses:Array<{mes:string;valor:string}>};
  const associacao=await getDb().query.associacoes.findFirst({where:eq(associacoes.id,Number(dados.associacaoId))});if(!associacao)return Response.json({message:"ASSOCIAÇÃO NÃO ENCONTRADA."},{status:404});
  let municipios:string[]=[];try{municipios=JSON.parse(associacao.municipiosJson||"[]");}catch{}const listaMunicipios=municipios.join(", ")||associacao.municipio||"MUNICÍPIOS A DEFINIR";const culturas=(dados.culturas||[]).join(", ")||"CULTURAS A DEFINIR";
  const resposta=await fetch(new URL("/modelo-plano-trabalho-associacao.docx",request.url));if(!resposta.ok)throw new Error("MODELO DO PLANO NÃO ENCONTRADO.");const arquivos=unzipSync(new Uint8Array(await resposta.arrayBuffer()));let documento=strFromU8(arquivos["word/document.xml"]);
  const endereco=[associacao.endereco,associacao.numero,associacao.bairro].filter(Boolean).join(", ");const enderecoPresidente=[associacao.presidenteEndereco,associacao.presidenteNumero,associacao.presidenteBairro].filter(Boolean).join(", ");
  const apresentacao=`O fortalecimento dos Arranjos Produtivos visa o desenvolvimento sustentável e o contínuo avanço das cadeias produtivas dos agricultores familiares. Este projeto tem como objetivo fortalecer a produção agrícola familiar nos municípios de ${listaMunicipios}, reduzir o êxodo rural, gerar renda, desenvolver as comunidades e ampliar a diversificação produtiva, com prioridade para as culturas de ${culturas}.`;
  const diagnostico=`Nos municípios de ${listaMunicipios}, o diagnóstico territorial considera as cadeias produtivas de ${culturas}. Serão trabalhados o conhecimento e a capacitação técnica, a gestão da produção, o preparo do solo, o plantio, o manejo, a colheita, o armazenamento, a comercialização e o beneficiamento por agroindústrias, promovendo o desenvolvimento econômico e sustentável.`;
  const justificativa=`A ${associacao.nome} é entidade sem fins lucrativos que atua no fortalecimento da agricultura familiar. O projeto dará continuidade e ampliará o apoio aos produtores rurais dos municípios de ${listaMunicipios}, considerando o potencial das culturas de ${culturas}, por meio de assistência técnica, capacitação, diversificação produtiva e fornecimento de insumos.`;
  const objetivoGeral=`Fortalecer os Arranjos Produtivos da Agricultura Familiar nos municípios de ${listaMunicipios}, por meio de assistência técnica continuada, capacitação produtiva e incentivo à diversificação das culturas de ${culturas}.`;
  const publico=`Produtores rurais dos municípios de ${listaMunicipios}, beneficiados com capacitação, apoio técnico, aperfeiçoamento produtivo e ações voltadas às culturas de ${culturas}.`;
  const abrangencia=`O Projeto será executado nos municípios de ${listaMunicipios}, abrangendo comunidades, propriedades da agricultura familiar, associações rurais e empreendimentos familiares previamente identificados. As ações ocorrerão nas propriedades e em espaços comunitários destinados a reuniões, capacitações, dias de campo, seminários e treinamentos técnicos.`;
  const mapa:Record<string,unknown>={NOME_ASSOCIACAO:associacao.nome,RAZAO_SOCIAL:associacao.razaoSocial||associacao.nome,CNPJ:associacao.cnpj||"",ENDERECO:endereco,MUNICIPIO_SEDE:associacao.municipio||"",UF:associacao.uf||"ES",CEP:associacao.cep||"",TELEFONE:associacao.telefone||"",CELULAR:associacao.celular||"",EMAIL:associacao.email||"",PRESIDENTE:associacao.presidenteNome||"",CPF_PRESIDENTE:associacao.presidenteCpf||"",RG_PRESIDENTE:"",ENDERECO_PRESIDENTE:enderecoPresidente,MUNICIPIO_PRESIDENTE:associacao.presidenteMunicipio||"",UF_PRESIDENTE:associacao.presidenteUf||"ES",CEP_PRESIDENTE:associacao.presidenteCep||"",EMAIL_PRESIDENTE:associacao.presidenteEmail||"",TELEFONE_PRESIDENTE:associacao.telefone||"",CELULAR_PRESIDENTE:associacao.celular||"",PERIODO_INICIO:dados.inicio,PERIODO_TERMINO:dados.termino,APRESENTACAO:apresentacao,DIAGNOSTICO:diagnostico,JUSTIFICATIVA_1:justificativa,JUSTIFICATIVA_2:"",OBJETIVO_GERAL:objetivoGeral,OBJETIVOS_ESPECIFICOS:(dados.etapas||[]).map(x=>x.objetivo).join("\n"),PUBLICO_1:publico,PUBLICO_2:"",ABRANGENCIA:abrangencia};
  (dados.etapas||[]).slice(0,3).forEach((l,i)=>Object.assign(mapa,{[`ETAPA_${i+1}`]:l.nome,[`OBJETIVO_${i+1}`]:l.objetivo,[`ACOES_${i+1}`]:l.acoes,[`METAS_${i+1}`]:l.metas,[`RESULTADOS_${i+1}`]:l.resultados}));
  (dados.objetivos||[]).slice(0,3).forEach((l,i)=>Object.assign(mapa,{[`MON_OBJ_${i+1}`]:l.objetivo,[`MON_QUANT_${i+1}`]:l.quantitativos,[`MON_QUAL_${i+1}`]:l.qualitativos,[`MON_FONTE_${i+1}`]:l.fonte,[`MON_COLETA_${i+1}`]:l.coleta,[`MON_RESP_${i+1}`]:l.responsavel,[`MON_PERIOD_${i+1}`]:l.periodicidade}));
  (dados.equipe||[]).slice(0,4).forEach((l,i)=>Object.assign(mapa,{[`EQ_CARGO_${i+1}`]:l.cargo,[`EQ_NUM_${i+1}`]:l.numero,[`EQ_ESC_SUP_${i+1}`]:l.escolaridade.toLocaleLowerCase("pt-BR").includes("superior")?"X":"",[`EQ_ESC_MED_${i+1}`]:l.escolaridade.toLocaleLowerCase("pt-BR").includes("médio")||l.escolaridade.toLocaleLowerCase("pt-BR").includes("medio")?"X":"",[`EQ_ATRIB_${i+1}`]:l.atribuicoes,[`EQ_SIM_${i+1}`]:"",[`EQ_NAO_${i+1}`]:"X",[`EQ_PERIODO_${i+1}`]:l.periodo,[`EQ_NATUREZA_${i+1}`]:l.natureza}));
  let total=0;(dados.itens||[]).slice(0,8).forEach((l,i)=>{total+=Number(l.valorTotal.replace(/\./g,"").replace(",","."))||0;Object.assign(mapa,{[`APL_ITEM_${i+1}`]:l.item,[`APL_DESC_${i+1}`]:l.descricao,[`APL_QUANT_${i+1}`]:l.quantidade,[`APL_UNID_${i+1}`]:l.unidade,[`APL_UNIT_${i+1}`]:moeda(l.valorUnitario),[`APL_TOTAL_${i+1}`]:moeda(l.valorTotal)})});mapa.TOTAL_GERAL=total.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});mapa.ORCAMENTO=`Orçamento total do projeto, conforme Plano de Aplicação de Recursos: ${mapa.TOTAL_GERAL}.`;
  (dados.repasses||[]).slice(0,2).forEach((l,i)=>{mapa[`REPASSE_MES_${i+1}`]=l.mes;mapa[`REPASSE_VALOR_${i+1}`]=moeda(l.valor)});mapa.DECLARACAO=`Na qualidade de representante legal do proponente, declaro, para fins de prova junto à ADERES, sob as penas da Lei, que inexiste situação de inadimplência que impeça a transferência de recursos públicos na forma deste Plano de Trabalho.\n\n${associacao.municipio||"Espírito Santo"}, ____ de __________________ de ______.\n\n${associacao.presidenteNome||"RESPONSÁVEL PELA INSTITUIÇÃO"}\nResponsável pela Instituição`;
  for(const[chave,valor]of Object.entries(mapa))documento=colocar(documento,chave,valor);documento=documento.replace(/\{\{[A-Z0-9_]+\}\}/g,"");arquivos["word/document.xml"]=strToU8(documento);
  for(const nomeXml of Object.keys(arquivos).filter(nome=>/^word\/(?:header|footer)\d+\.xml$/.test(nome))){let conteudo=strFromU8(arquivos[nomeXml]);for(const[chave,valor]of Object.entries(mapa))conteudo=colocar(conteudo,chave,valor);conteudo=conteudo.replace(/\{\{[A-Z0-9_]+\}\}/g,"");arquivos[nomeXml]=strToU8(conteudo)}
  const saida=zipSync(arquivos,{level:6});const nome=`PLANO_DE_TRABALHO_${associacao.nome.replace(/[^A-Z0-9]+/gi,"_")}.docx`;
  return new Response(saida,{headers:{"content-type":"application/vnd.openxmlformats-officedocument.wordprocessingml.document","content-disposition":`attachment; filename=\"${nome}\"`}});
 }catch(error){console.error("gerar_plano_associacao",error);return Response.json({message:error instanceof Error?error.message:"NÃO FOI POSSÍVEL GERAR O PLANO DE TRABALHO."},{status:500})}
}
